import {rollDice} from '@wandering-monstrum/perchance-engine';
import {nameForCreature} from './dolmenwood-names.js';

// Per-species lair chance, hoard-eligibility, and carried-possession eligibility,
// sourced from the Dolmenwood Monster Book's own encounter tables (via a fan-made
// Perchance generator that encodes them). Coverage is comprehensive — nearly every
// creature in dolmenwood-encounters.txt has an entry, including the many with
// lairChance: 0 (roaming bands and plain animals that the sourcebook never places in
// a lair on the wilderness tables — goblins, wolves, deer, etc). hasPoss marks
// species that carry an individual item even when encountered away from a lair.
// hoardTier/possession item are resolved at roll time from the monster's level, since
// we reuse our own generic Treasure03/46/79 tables rather than the sourcebook's item
// tables.
export const LAIR_DATA = {
    "ANT, GIANT": {lairChance: 0.3, hasHoard: true, hasPoss: false},
    "ANTLER WRAITH": {lairChance: 0.75, hasHoard: true, hasPoss: false},
    BANSHEE: {lairChance: 0.1, hasHoard: true, hasPoss: false},
    BARROWBOGEY: {lairChance: 0.25, hasHoard: true, hasPoss: false},
    BASILISK: {lairChance: 0.4, hasHoard: true, hasPoss: false},
    "BAT, GIANT": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    "BAT, VAMPIRE": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    BEAR: {lairChance: 0.3, hasHoard: false, hasPoss: false},
    "BLACK TENTACLES": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    BOAR: {lairChance: 0.0, hasHoard: false, hasPoss: false},
    "BOG CORPSE": {lairChance: 0.35, hasHoard: true, hasPoss: false},
    "BOG SALAMANDER": {lairChance: 0.25, hasHoard: true, hasPoss: false},
    BOGGIN: {lairChance: 0.25, hasHoard: true, hasPoss: false},
    BRAINCONK: {lairChance: 0.0, hasHoard: false, hasPoss: false},
    BRAMBLING: {lairChance: 0.0, hasHoard: false, hasPoss: true},
    "BREGGLE-LONGHORN": {lairChance: 0.1, hasHoard: true, hasPoss: true},
    "BREGGLE-SHORTHORN": {lairChance: 0.2, hasHoard: true, hasPoss: true},
    "BURROWING BEETLE": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    "CARRION WORM": {lairChance: 0.3, hasHoard: true, hasPoss: false},
    "CATFISH, GIANT": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    "CENTAUR-BESTIAL": {lairChance: 0.25, hasHoard: true, hasPoss: true},
    "CENTAUR-SYLVAN": {lairChance: 0.0, hasHoard: false, hasPoss: true},
    "CENTIPEDE, GIANT": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    COBBIN: {lairChance: 0.15, hasHoard: true, hasPoss: true},
    COCKATRICE: {lairChance: 0.25, hasHoard: true, hasPoss: false},
    "CRAB, GIANT": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    CROOKHORN: {lairChance: 0.25, hasHoard: true, hasPoss: true},
    "DEORLING-DOE": {lairChance: 0.0, hasHoard: false, hasPoss: true},
    "DEORLING-STAG": {lairChance: 0.0, hasHoard: false, hasPoss: true},
    "DEVIL GOAT": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    "DRUNE-AUDRUNE": {lairChance: 0.0, hasHoard: true, hasPoss: true},
    "DRUNE-BRAITHMAID": {lairChance: 0.2, hasHoard: false, hasPoss: true},
    "DRUNE-COTTAGER": {lairChance: 0.2, hasHoard: false, hasPoss: true},
    "DRUNE-DRUNEWIFE": {lairChance: 0.3, hasHoard: true, hasPoss: true},
    "ELF-COURTIER": {lairChance: 0.0, hasHoard: false, hasPoss: true},
    "ELF-KNIGHT": {lairChance: 0.0, hasHoard: false, hasPoss: true},
    "ELF-WANDERER": {lairChance: 0.0, hasHoard: false, hasPoss: true},
    "FAIRY HORSE": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    "FALSE UNICORN": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    "FIRE BEETLE, GIANT": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    "FLY, GIANT": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    FOMORIAN: {lairChance: 0.35, hasHoard: true, hasPoss: false},
    GALOSHER: {lairChance: 0.75, hasHoard: true, hasPoss: false},
    "GELATINOUS HULK": {lairChance: 0.0, hasHoard: false, hasPoss: true},
    GHOUL: {lairChance: 0.2, hasHoard: true, hasPoss: false},
    GLOAM: {lairChance: 0.2, hasHoard: true, hasPoss: false},
    GOBLIN: {lairChance: 0.0, hasHoard: false, hasPoss: true},
    GRIFFON: {lairChance: 0.3, hasHoard: true, hasPoss: false},
    GRIMALKIN: {lairChance: 0.1, hasHoard: true, hasPoss: true},
    HARPY: {lairChance: 0.25, hasHoard: true, hasPoss: true},
    HARRIDAN: {lairChance: 0.4, hasHoard: true, hasPoss: true},
    "HEADLESS RIDER": {lairChance: 0.0, hasHoard: true, hasPoss: false},
    "INSECT SWARM": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    "JACK-O'-LANTERN": {lairChance: 0.15, hasHoard: true, hasPoss: false},
    KELPIE: {lairChance: 0.0, hasHoard: false, hasPoss: false},
    "KILLER BEE": {lairChance: 0.3, hasHoard: true, hasPoss: false},
    "LEECH, GIANT": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    MADTOM: {lairChance: 0.25, hasHoard: true, hasPoss: false},
    MANTICORE: {lairChance: 0.2, hasHoard: true, hasPoss: false},
    "MARSH LANTERN": {lairChance: 1.0, hasHoard: true, hasPoss: false},
    MERFAUN: {lairChance: 0.1, hasHoard: true, hasPoss: true},
    MOGGLEWOMP: {lairChance: 0.5, hasHoard: true, hasPoss: false},
    MOSSLING: {lairChance: 0.5, hasHoard: true, hasPoss: true},
    "MOULD ORACLE": {lairChance: 0.65, hasHoard: true, hasPoss: true},
    MUGWUDGE: {lairChance: 0.33, hasHoard: true, hasPoss: false},
    NUTCAP: {lairChance: 0.5, hasHoard: true, hasPoss: false},
    "OCHRE SLIME-HULK": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    OGRE: {lairChance: 0.4, hasHoard: true, hasPoss: true},
    "ONYX BLOB": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    OWLBEAR: {lairChance: 0.0, hasHoard: false, hasPoss: false},
    PERYTON: {lairChance: 0.25, hasHoard: true, hasPoss: false},
    "PIKE, GIANT": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    "POOK MOREL": {lairChance: 0.25, hasHoard: true, hasPoss: true},
    "RAPACIOUS BEETLE": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    "RAT, GIANT": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    "RED DEER": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    REDCAP: {lairChance: 0.0, hasHoard: false, hasPoss: true},
    REDSLOB: {lairChance: 0.0, hasHoard: false, hasPoss: true},
    "ROOT THING": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    SCARECROW: {lairChance: 0.0, hasHoard: false, hasPoss: true},
    SCRABEY: {lairChance: 0.15, hasHoard: true, hasPoss: true},
    SHADOW: {lairChance: 0.4, hasHoard: true, hasPoss: false},
    "SHAGGY MAMMOTH": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    "SHAPE-STEALER": {lairChance: 0.2, hasHoard: true, hasPoss: false},
    SKELETON: {lairChance: 0.0, hasHoard: false, hasPoss: true},
    "SNAIL, GIANT-MUTANT": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    "SNAIL, GIANT-PSIONIC": {lairChance: 0.35, hasHoard: false, hasPoss: false},
    "SNAKE—ADDER": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    SPECTRE: {lairChance: 0.8, hasHoard: true, hasPoss: false},
    "SPINNING SPIDER, GIANT": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    SPRITE: {lairChance: 0.15, hasHoard: true, hasPoss: false},
    STIRGE: {lairChance: 0.0, hasHoard: false, hasPoss: false},
    "SWAMP SLOTH": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    "SWAMP SPIDER, GIANT": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    "TALKING ANIMAL": {lairChance: 0.15, hasHoard: true, hasPoss: false},
    "TOAD, GIANT": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    TREOWERE: {lairChance: 0.5, hasHoard: true, hasPoss: false},
    TROLL: {lairChance: 0.3, hasHoard: true, hasPoss: false},
    "UNICORN-BLESSED": {lairChance: 0.0, hasHoard: false, hasPoss: true},
    "UNICORN-CORRUPT": {lairChance: 0.0, hasHoard: false, hasPoss: true},
    "WATER TERMITE, GIANT": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    "WEASEL, GIANT": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    WEREWOLF: {lairChance: 0.25, hasHoard: true, hasPoss: false},
    "WICKER GIANT": {lairChance: 0.5, hasHoard: false, hasPoss: false},
    WIGHT: {lairChance: 0.5, hasHoard: true, hasPoss: false},
    WITCH: {lairChance: 0.2, hasHoard: true, hasPoss: true},
    "WITCH OWL": {lairChance: 0.25, hasHoard: true, hasPoss: false},
    WODEWOSE: {lairChance: 0.0, hasHoard: false, hasPoss: true},
    WOLF: {lairChance: 0.0, hasHoard: false, hasPoss: false},
    "WOLF, DIRE": {lairChance: 0.0, hasHoard: false, hasPoss: false},
    WOODGRUE: {lairChance: 0.0, hasHoard: false, hasPoss: true},
    WRONGUNCLE: {lairChance: 0.0, hasHoard: false, hasPoss: true},
    "WYRM-BLACK BILE": {lairChance: 0.5, hasHoard: true, hasPoss: false},
    "WYRM-BLOOD": {lairChance: 0.5, hasHoard: true, hasPoss: false},
    "WYRM-PHLEGM": {lairChance: 0.5, hasHoard: true, hasPoss: false},
    "WYRM-YELLOW BILE": {lairChance: 0.5, hasHoard: true, hasPoss: false},
    YEGRIL: {lairChance: 0.0, hasHoard: false, hasPoss: false},
    YICKERWILL: {lairChance: 0.9, hasHoard: true, hasPoss: false},
};

// The four Wyrm species (deadly, near-mythic threats) each have a specific,
// sourcebook-defined weakness. Flat list, evaluated for any WYRM-* encounter
// regardless of lair status.
export const WYRM_VULNERABILITIES = [
    'exposure to daylight',
    'the presence of a pure-hearted virgin',
    'hallowed ground',
    'the light of the full moon',
    'unicorn horns',
    'the stench of rotting fish',
    'atheist philosophy',
    'witch magic',
];
const WYRM_SPECIES = new Set(['WYRM-BLACK BILE', 'WYRM-BLOOD', 'WYRM-PHLEGM', 'WYRM-YELLOW BILE']);

// Hand-written physical/behavioral traits for a curated, high-frequency subset of
// species (the ones most likely to come up regardless of region). Original text,
// not drawn from any published sourcebook. Species without an entry here still get
// accurate lair/hoard mechanics from LAIR_DATA above, just no trait line.
export const SPECIES_TRAITS = {
    'ANTLER WRAITH': [
        'Wields a scythe or ancient sword (damage as per touch).',
        'Utters a single, sinister word, mantra-like.',
        'Skull wreathed in blue flame.',
        'Jewels in eye sockets (500gp each, cursed: –4 Strength).',
        'Antlers draped with shrivelled human intestines.',
        'Shrieks upon sight of living souls.'
    ],
    BANSHEE: [
        'Seductive, youthful beauty.',
        'Throat slit. Icy, blue blood drips from the wound.',
        'Sings forgotten ballads in an otherworldly soprano.',
        'Spectral skin wreathed with frost and patched with moss.',
        'Scent of ancient floral perfumes.',
        'Nearby plants rime with crackling frost.'
    ],
    BARROWBOGEY: [
        'Wears a cracked clay pot as a helmet, chipped nose-first.',
        'Fingers are stained black with old grave-dirt.',
        'Carries a fistful of bent iron nails as currency.',
        'Giggles in short, wheezing bursts when excited.',
        '1d4+2 pots, precariously stacked on shoulders.',
        'Cheeky, grinning face painted on head-pot.',
        'Teapot-head. Pours and drinks cups of steaming tea.',
        'Croaks like a frog.',
        'Wears pots on feet and hands, like shoes and mittens.',
        'Hops on all fours, leaps, and tumbles.',
    ],
    BASILISK: [
        'Midway through shedding skin.',
        'Inflatable vocal sac in throat.',
        'Cobra-like hood that expands when threatened.',
        'Small vestigial wings.',
        'Bloody tears spill from eyes.',
        'Preceded by the scent of petrichor.'],
    'BLACK TENTACLES': [
        'Straggly, hand-like appendages at ends of tentacles.',
        'Water around the monster bubbles and roils.',
        'Contact leaves black stains for 1d6 days.',
        'Covered in rubbery nodules.',
        'Reeks of carrion.',
        'Tentacles ridged with malicious, purple eyes.',
    ],
    'BOG CORPSE': [
        'Headless.',
        'Draped with dank pondweed.',
        'Covered with crabs and bog-snails.',
        'Flesh rotted away, almost skeletal.',
        'Eyes burning with a flickering green light.',
        'Swollen and leech-ridden.',
    ],
    'BOG SALAMANDER': [
        'Purplish veins and organs visible through skin.',
        'Coral-like air-gills fluttering around throat.',
        'Emits a choked gurgling as it hunts.',
        'Rows of blisters along back, filled with scarlet jelly.',
        'Slimy, yellow tongue lolling.',
        'Clamouring, human-like hands',
    ],
    BOGGIN: [
        'Dead tree branches arranged like antlers.',
        'Weed-hair full of squirming worms and tadpoles.',
        'Rows of pendulous teets.',
        'Long, lumpy tail, ending in a tuft of pondweed.',
        'Sickening, rotting stench.',
        'Adorned with necklaces of human bones',
    ],
    BRAINCONK: [
        'Keens and purrs when attacking.',
        'Tiny human faces (of victims) on upper side.',
        'Giggles when spotted.',
        'Upper side striated black.',
        'Several mouths with tiny, shiny teeth.',
        'Covered in symbiotic, purple mould.',
    ],
    BRAMBLING: [
        'Crown of thorns.',
        'Intermingled with pretty wildflowers.',
        'Thick, charred, stump integrated in torso.',
        'Beard of holly.',
        'Bird’s nest in chest cavity; may contain a clutch of eggs.',
        '“Face” covered with bright yellow fungus.',
    ],
    'BREGGLE-LONGHORN': [
        'Forward-pointing horns (an especially noble trait).',
        'Deep red eyes.',
        'A golden or silver tooth.',
        'Odd pet: a monkey, sprite, or fanged sheep.',
        'Wears a monocle.',
        'Long, lustrous, beautifully groomed fur.',
    ],
    'BREGGLE-SHORTHORN': [
        'Wears an eye patch.',
        'Broken or jutting teeth.',
        'Fur and eyes of midnight black.',
        'Wooden leg.',
        'Three-horned.',
        'Large, misshapen skull with odd lumps.',
    ],
    'CENTAUR-BESTIAL': [
        'Hairless, indigo skin and flaming, yellow eyes.',
        'Patchy, white fluff.',
        'Fronds of writhing, snake-like “hair” upon head.',
        'Cyclops. Eye pulses green and purple.',
        'Covered in weeping boils and ulcers.',
        'Stunted, three-fingered arm protruding from chest.',
    ],
    'CENTAUR-SYLVAN': [
        'Decorated with hunting trophies.',
        'Clad in wolf-skin.',
        'Eyes of piercing blue, tangle of black hair.',
        'Silver-dappled flanks.',
        'Collection of fantastic hunting and drinking horns.',
        'Battle-beaten helmet with ornate antlers.',
    ],
    COBBIN: [
        'Smokes a long pipe.',
        'Hat keeps slipping down over eyes.',
        'Whistles and sings little ditties between sentences.',
        'Wicker basket on back, laden with straw and kindling.',
        'Thick woolly jumper with far too long arms.',
        'Iron collar around neck (placed by crookhorns).',
    ],
    COCKATRICE: [
        'Comb resembles an elaborate crown.',
        'Enormous, feathery beard.',
        'Cackles relentlessly.',
        'Scales shine in a rainbow of colour.',
        'Large, bone-like spurs on legs.',
        'Bloated, serpentine tail.',
    ],
    CROOKHORN: [
        'One horn is snapped off short, the stump filed smooth.',
        'Wears a stolen dueling glove on the off-hand.',
        'Reeks of cheap wine and pipe-smoke.',
        'Keeps a tally of grudges scratched into a wooden tablet.',
        'Milky white, oozing eyes.',
        'Patchy fur and flaking, grey skin.',
        'One horn snapped off.',
        'Bright orange, red or purple fur—maybe natural or dyed.',
        'Speaks in a sinister whisper, giggles maniacally.',
        'Bellows, gurgles, erratically rolls eyes',
    ],
    CRYSTALOID: [
        'Face carved into head.',
        'Spider-webbed with fracture lines.',
        'Multi-coloured lights sparkle inside.',
        'Movement sounds like wind chimes.',
        'Body a patchwork of different gems.',
        'Cloak of bioluminescent fungi.',
    ],
    'DEORLING-DOE': [
        'Dappled skin.',
        'Long necklaces of wooden beads and bones.',
        'Bodice of moss, laced with creepers.',
        'Golden hair and violet eyes.',
        'Eyes wrapped, single painted eye on wrapping.',
        'Cloak of iridescent sprite wings.',
    ],
    'DEORLING-STAG': [
        'Horrid scars amid patches of shredded fur.',
        'Antlers draped with shedding velvet.',
        'One antler broken off, stump wrapped with moss.',
        'Missing hand, sword bound to wrist with leather straps.',
        'Short, pointed horn between antlers.',
        'Ragged breath, long tongue lolls from drooling mouth',
    ],
    'DEVIL-GOAT': [
        'Central eye weeps bloody tears.',
        'Hooves spark red flames.',
        'Bleating sounds like mocking laughter.',
        'Fur grizzled with patches of white.',
        'Crowned with a wreath of ivy.',
        'Ear tag bearing the coat-of-arms of a longhorn noble.',
    ],
    'DRUNE-BRAITHMAID': [
        'Albino—white hair and pink eyes.',
        'Human knuckle bones hanging from silver earrings.',
        'Densely freckled.',
        'Wears a cloak of crow feathers.',
        'Clad in diaphanous gauze, spattered with blood.',
        'Crown of holly and ivy',
    ],
    'DRUNE-COTTAGER': [
        'Emaciated and addled by mushroom brew.',
        'Necklace of owl skulls.',
        'Crown of antlers.',
        'Wears a featureless clay mask.',
        'Grizzled plaits cascading from his hood.',
        'Skin covered with occult markings. (Tattoos? Paint?)',
    ],
    'DRUNE-DRUNEWIFE': [
        'Dressed in rabbit skins.',
        'Beaming and buxom.',
        'Frail and waif-like.',
        'Hair in long plaits to the waist.',
        'Blind, rheumy eyes; navigates by magic.',
        'Moves without sound; opposing side 4-in-6 surprised.',
    ],
    'ELF-KNIGHT': [
        'Opalescent skin dusted with powdered crystal.',
        'Armour of plated ice shards.',
        'Golden feathered nightingale on shoulder.',
        'Hair of silver filigree.',
        'Amber or violet eyes without pupils.',
        'Armour of scintillating fish scales.',
        'Armor is centuries old, without a single scratch upon it.',
        'Speaks of recent centuries as though they were yesterday.',
        'Regards mortals with a mixture of pity and faint amusement.',
        'Blade never seems to need sharpening.',
    ],
    'ELF-COURTIER': [
        'Spectral butterflies flitting around hair.',
        'Leaves a trail of petals, snowflakes, or light motes.',
        'Changes costume with the snap of a finger.',
        'Clad in gossamer of woven radiance or shadow.',
        'Speaks without moving mouth, makes odd gestures.',
        'Extravagantly lush hair—8′ long, drifts behind.',
        'Dressed in fashions no mortal court has seen in a hundred years.',
        'Every gesture is precise, almost theatrical.',
        'Laughs at jokes not yet spoken.',
        'Never quite steps in mud, however deep.',
    ],
    'ELF-WANDERER': [
        'Travels without visible supplies, never hungry, never cold.',
        'Hums a tune that seems to shift the surrounding birdsong.',
        'Footprints vanish behind them within a few steps.',
        'Carries no weapon, and seems unconcerned by the lack.',
        'Hair made of slender willow leaves.',
        'Utterly hairless, skin shimmers.',
        'Pearlescent eyes without pupils.',
        'Skin hue phases between alabaster, slate, and ebony.',
        'Dressed in a shift of glimmering snowflakes.',
        'Eyes reflect an eternal sunset.',
    ],
    'FAIRY HORSE': [
        'Coat shifts color subtly with the light, never quite the same twice.',
        'Hoofbeats make no sound on any surface.',
        'Mane is woven through with tiny, fading stars.',
        'Approaches only those it has already decided to trust.',
        'Surrounded by a primeval, lambent glow.',
        'Tail and mane of gold.',
        'Hooves flash silver when galloping.',
        'Feathered rump.',
        'Eyes of flaming violet.',
        'Six legs.',
    ],
    FOMORIAN: [
        'Sweats a sickly-sweet slime.',
        'Tentacular beard.',
        'Covered in oozing sores.',
        'White light fills eye socket.',
        'Gemstones embedded in skin.',
        'Gives nonsense, faux-intellectual advice.',
    ],
    GALOSHER: [
        'Mouths constantly drooling black bile.',
        'Illusory forms still have lamprey teeth.',
        'Hiccups bubbles of dream stuff.',
        'Emits a pleading whine.',
        'Reeks of melancholy.',
        'Tiny human faces inside each lamprey',
    ],
    GARGOYLE: [
        'Covered in ivy.',
        'Patched with moss and lichen.',
        'Damaged: missing limb, nose, claw, etc.',
        'Carved from elegant, veined marble.',
        'Decorates itself with necklaces and trinkets.',
        'Rolling eyes, lashing tongue, and slavering maw.',
    ],
    'GELATINOUS HULK': [
        'Phosphorescent.',
        'Covered in nodules and wobbly tentacles.',
        'Drowsy; patched with moss and lichen.',
        'Elf skeleton drifting in belly.',
        'Daintily festooned with vines and pondweed.',
        'Arms only emerge from body when chasing prey.',
    ],
    GHOUL: [
        'Fingernails are worn to ragged points from digging.',
        'Jaw hangs slightly unhinged, clicking as it breathes.',
        'Reeks of fresh-turned earth.',
        'Freezes mid-motion when spoken to directly, listening.',
        'Canine-like snout.',
        'Draped in rotten finery.',
        'Constantly drooling blood.',
        'Fingers are far too long.',
        'Patchwork clothing from a dozen victims.',
        'Voice of a child',
    ],
    GLOAM: [
        'Dressed in finery (the garments fly with the flock).',
        'Smoulders when exposed to light.',
        'Hovers ominously a few inches above the ground.',
        'Blood drips incessantly from eyes.',
        'Bleached, white bones with small clumps of feathers.',
        'Shadow moves independently, expressing emotions.',
    ],
    GOBLIN: [
        'Warpaint smeared in dried berry juice, half rubbed off.',
        'Wears a trophy — a boot, a glove — taken from a slain traveler.',
        'Argues constantly with the goblin nearest in rank.',
        'Carries a rusted bell looted from some farmstead.',
        'Grinning, feline face with wiry whiskers.',
        'Bristly, boar-like face with protruding tusks.',
        'Wispy beard of thistledown. Speaks in rhyme.',
        'Long, mouse-like nose, constantly twitching and sniffing.',
        'Pointed ears and nose. Mouth of wicked, needle fangs.',
        'Goggle-eyed. Whisking cat’s tail.',
    ],
    GRIMALKIN: [
        'Grooms an elaborately curled whisker between sentences.',
        'Carries a tiny, absurdly ornate walking cane.',
        'Answers every question with a question of its own.',
        'Vanishes into shadow mid-sentence, reappearing to finish the thought.',
        'Dressed in pirate garb, complete with a tricorn hat.',
        'Eyes shift between violet, green, and amber.',
        'Fur constantly stands on end, as if electrified.',
        'Licks face and preens whiskers with long, pink tongue.',
        'Snacks on a seemingly limitless supply of pickled rats.',
        'Smirks, snickers, and stifles laughs at all mortals say.',
    ],
    HARPY: [
        'Dressed in tattered priestly robes.',
        'Constantly humming a tune.',
        'Reeks of sulphur.',
        'Cradles a musical instrument.',
        'Feathers white as snow.',
        'Visage of an old man.',
    ],
    HARRIDAN: [
        'Central third eye, bulbous and oozing green pus.',
        'Clad in a patchwork apron of human scalps.',
        'Empty eye sockets, magical sight.',
        'Gargantuan, hairy nostrils, constantly sniffing.',
        'Lurid purple skin, flaking and blistered.',
        'Clumps of matted hair writhe like serpents.',
    ],
    'HEADLESS RIDER': [
        'Stag’s or ram’s skull hovers above severed neck.',
        'Gore drips from neck and head.',
        'Wreathed in eerie violet flame.',
        'Accompanied by the sound of a clinking coin purse.',
        'Electrical sparks fly from wicked, jangling spurs.',
        'Ornate plate armour, engraved with demonic visages.',
    ],
    "JACK-O'-LANTERN": [
        'Cap peaked at an odd, unsettling angle.',
        'Eyes pulse in slow, hypnotic rhythm.',
        'Leaves a faint, sweetish smell of rot in passing.',
        'Flesh glistens, half-translucent in dim light.',
        'Cap peaked like a wizard’s hat.',
        'Twisted, talon-like fingers.',
        'Eyes pulse purple and pink when communicating.',
        'Blubbering, oozing, black maw.',
        'Semi-transparent flesh reveals an inner illumination.',
        'Cap crawling with delicate, magenta worms.',
    ],
    KELPIE: [
        'Mane is tangled thick with pondweed.',
        'Eyes hold a faint, unnatural green glow.',
        'Hooves are oddly jointed, turned the wrong way.',
        'Coat stays damp no matter how long out of the water.',
        'Dappled green and brown flanks.',
        'Pearly eyes.',
        'Covered in small snails and shellfish.',
        'Glimmers as if in moonlight.',
        'Eyes aflame with an unholy light.',
        'Eyes and tongue rolling drunkenly.',
    ],
    MADTOM: [
        'Whiskers twitch constantly, tasting the air.',
        'Skin is slick and faintly luminous in the dark.',
        'Eyes sit high and wide, built for looking up from below.',
        'Moves in short, twitchy bursts, never smoothly.',
        'Frilly gills change colour with mood.',
        'Two pupils in each eye.',
        'Tongue pokes out to lick eyeballs.',
        'Row of fin-like proto-hands along belly.',
        'Shedding skin: flaky scales drop off.',
        'Milky white, translucent flesh. Pink eyes and organs.',
    ],
    MANIKIN: [
        'No discernible head.',
        'Chessboard on chest, chess pieces for fingers.',
        'Face of a young boy, carefully carved from oak.',
        'China chamberpot perched atop shoulders, as a head.',
        'Quietly mutters a single, creaking word: “Hasturiel”.',
        'Dressed in ill-fitting petticoats and a flowery smock.',
    ],
    MANTICORE: [
        'Face carries an expression too human for comfort.',
        'Tail spikes click faintly with restless movement.',
        'Preens its mane with obsessive care.',
        'Speaks in a soft, cultured voice, oddly out of place.',
        'Three rows of teeth.',
        'Luscious golden locks.',
        'Bushy tail, held upright.',
        'Needling, whiny voice.',
        'Face of an oversized toddler.',
        'Emaciated, bones pressing against skin.',
    ],
    'MARSH LANTERN': [
        'Light flickers in time with a heartbeat no one else can hear.',
        'The face within the glow keeps shifting, never settling.',
        'Trailing wisps of glowing vapor mark its passage.',
        'Draws in tight and brightens sharply when threatened.',
        'Tears of yellow ectoplasm drift from weeping face.',
        'Joined souls—two faces, partially amalgamated.',
        'Emits a lurid ultraviolet radiance.',
        'Tethered to its corpse by trailers of lank lichen.',
        'Innocent, smiling face of a child.',
        'Face morphs between rotting corpse and beautiful maid.',
    ],
    MERFAUN: [
        'Beard is braided through with small shells and river-glass.',
        'Grins constantly, showing blunt, goatish teeth.',
        'Horns are polished smooth by years in the water.',
        'Smells faintly of brine and pipe-smoke.',
        'Goat-like eyes.',
        'Dressed in armour constructed from reeds (AC 13).',
        'Upper body covered in thick, weed-like hair.',
        'Translucent, pale blue flesh.',
        'Strong body odour of dead fish.',
        'Necklace fashioned from sea snail shells.',
    ],
    MOGGLEWOMP: [
        'A vast, soft bulk that leaves no footprints.',
        'Mouth opens sideways, lined in concentric teeth.',
        'Communicates in low, resonant hums felt in the chest.',
        'Skin shifts color slowly to match its surroundings.',
        'Wiry, 6′-long whiskers.',
        'Frilly gingham bonnet.',
        'Quivering, purple, rubbery lips.',
        'Twirls its oiled moustache.',
        'Wears a neck-ruff or bow-tie.',
        'Bright cyan fur.',
    ],
    MOSSLING: [
        'Small, round body entirely carpeted in soft green moss.',
        'Leaves a faint trail of spores when startled into a run.',
        'Voice is a papery whisper, easily lost in wind.',
        'Curls into a ball resembling a mossy stone when frightened.',
        'Pack full of stinky swine-cheese.',
        'Curious, bendy hat of red felt.',
        'Butt naked.',
        'Dried mushroom caps strung around neck.',
        'Dainty birch-bark gloves and booties.',
        'Speaks in a high-pitched wheeze',
    ],
    'MOULD ORACLE': [
        'Eyes have gone milky-white, clouded like fungal caps.',
        'Speaks in a slow drone, half a chant.',
        'Fingers leave a faint trail of spores on anything touched.',
        'Sits motionless for long stretches, then moves all at once.',
        'Rough clay mask with dangling conkers.',
        'Pulsating puffballs in place of eyes.',
        'Yellow spores drifting from mouth and ears.',
        'Constant oracular babbling.',
        'Hands formed entirely of knotted mycelia.',
        'Naked, skin daubed with glowing green slime.',
    ],
    MUGWUDGE: [
        'Tusks are yellowed and chipped from years of rooting.',
        'Bristled hide is matted with dried mud and burrs.',
        'Breath comes in wet, heavy snorts.',
        'Eyes are small, sunk deep in folds of hide.',
        'Fringes of purple, symbiotic lichen.',
        'Warty pustules covering back.',
        'One eye bulbous and oozing black pus.',
        'Swollen, throbbing tongue lolls from mouth.',
        'Eyeless, senses by smell and hearing alone.',
        'Six-legged. Massive front legs and stumpy rear legs.',
    ],
    NUTCAP: [
        'No bigger than a fist, rides a trained field-mouse.',
        'Voice like a creaking acorn shell.',
        'Collects lost buttons, believing them to be coins.',
        'Vanishes into leaf-litter the instant it is startled.',
        'Scintillating compound eyes.',
        'Creaks like wet wood as it moves.',
        'Leafy shoots growing from joints.',
        'Symbiotic hornets’ nest (treat as an insect swarm—p115).',
        'Burred hands (can be used as clubs).',
        'Eye-like whorls over whole body.',
    ],
    'OCHRE SLIME-HULK': [
        'Surface ripples slowly, never fully still.',
        'Leaves a faint, acid-yellow sheen on anything it brushes.',
        'No visible eyes, yet it never seems to lose track of prey.',
        'Moves with a slow, dragging, deliberate certainty.',
        'Skull-like face.',
        'Covered in sucking, slurping orifices.',
        'Acidic, citrus reek.',
        'Spore-stalks are hand-like and eye-like.',
        'Humanoid skeleton in hollow lattice at centre of torso.',
        'Writhing cluster of worm-like tentacles at front of body',
    ],
    OGRE: [
        'Horns are notched and chipped from old brawls.',
        'Breath reeks of rancid meat.',
        'Carries a sack that clinks and shifts as it moves.',
        'Speaks in short, blunt grunts, rarely a full sentence.',
        'Jaw completely unhinges.',
        'Emaciated torso reveals last meal.',
        'Cooking pot worn as a helm.',
        'Horns twist and branch like antlers.',
        'Self-inflicted ritual scarification.',
        'Hide clothing fashioned from unicorn skin.',
    ],
    'ONYX BLOB': [
        'Surface is glassy-black, reflecting distorted shapes.',
        'Moves in slow, deliberate ripples, never hurried.',
        'Leaves a faint chemical tang in the air.',
        'Seems to lean toward warmth and motion instinctively.',
        'Writhing with weird, human-like faces.',
        'Leaves a trail of caustic slime, dissolving plant life.',
        'Iridescent purple sheen.',
        'Emits horrible slurping sounds.',
        'Semi-transparent, with an awful, glaring eye in its centre.',
        'Moves in lurching, wobbling leaps.',
    ],
    PERYTON: [
        'Antlers are notched with old, healed scars.',
        'Wings beat in a heavy, deliberate rhythm.',
        'Eyes track prey with unsettling, birdlike stillness.',
        'Casts an oddly elongated shadow, even at midday.',
        'Antlers resemble grasping hands.',
        'Fangs too large for mouth.',
        'Garishly colourful plumage.',
        'Leather collar around neck.',
        'Casts the shadow of a human.',
        'Has shed its antlers.',
    ],
    'POOK MOREL': [
        'No taller than a boot, easy to miss in leaf litter.',
        'Cap tilts and bobs like a tiny, curious head.',
        'Giggles in short, high-pitched bursts.',
        'Moves in quick, darting hops between cover.',
        'Formations on cap that resemble human faces.',
        'Cap oozes nectar that attracts ants and wasps.',
        'Dressed in a stolen silk glove.',
        'Wears a lady’s purse, adapted into a backpack.',
        'Feathery cap which is lifted up by breezes.',
        'Wears thimbles as shoes.',
    ],
    REDCAP: [
        'Cap is soaked dark red, dripping steadily.',
        'Iron-shod boots strike sparks on stone.',
        'Counts kills aloud under its breath.',
        'Carries a whetstone worn to a sliver from constant use.',
        'Constantly giggling.',
        'Hairy, shoeless feet.',
        'Eyes like emeralds.',
        'Sings lullabies while administering a beating.',
        'Carries a human infant in a wicker basket.',
        'Shiny, red, leather boots with brass buckles.',
    ],
    REDSLOB: [
        'Drips slowly, leaving small red stains below.',
        'Surface catches light in a slick, oily sheen.',
        'Recoils slightly at loud noise, cautious despite its bulk.',
        'Smells faintly sweet, almost like spoiled fruit.',
        'Eye-like organs on wobbly stalks.',
        'Sporadically wracked with quivering.',
        'Surrounded by a pink vapour.',
        'Suit of armour embedded in ooze mass.',
        'Mimics the forms of those it encounters.',
        'Dotted with throbbing white globes.',
    ],
    'ROOT THING': [
        'Fingers taper into long, grasping roots.',
        'Bark-like skin is deeply fissured and dry.',
        'Moves with a slow, creaking, deliberate gait.',
        'Leaves a trail of disturbed, freshly turned earth.',
        'Long, grasping fingers.',
        'Eye-like whorls on body. Maybe they really are eyes?',
        'Mass of floppy foliage.',
        'Gaping, mouth-like orifice which moans and belches.',
        'Covered in grotesque nodules and limp, stunted arms.',
        'Long, pointy nose.',
    ],
    SCARECROW: [
        'Straw stuffing spills from a seam at the throat.',
        'Painted grin is cracked into something crueler.',
        'Turns to track movement long after it should be still.',
        'Crows perch on its shoulders undisturbed.',
        'Chuckles and sighs between sentences.',
        'Inadvertently mutters “juicy brains” in conversation.',
        'Sacking eroded, composed entirely of straw/brambles.',
        'Plucks and neatly re-stuffs stray straws.',
        'One leg missing, walks with a crutch.',
        'Partially burned, straw and sacking charred.',
    ],
    SCRABEY: [
        'Chatters incessantly in a language of clicks and whistles.',
        'Wears a necklace strung with tiny animal skulls.',
        'Twitchy, darting eyes never settle on one thing.',
        'Smells faintly of sulfur and burnt fur.',
        'Wears a quizzical wooden mask.',
        'Smokes green Mogglemoss (DPB) in a long, clay pipe.',
        'Listens through an ivory horn.',
        'Braided beard, down to the knees.',
        'Calls strangers “Palanquin” and friends “Spontywiff”.',
        'Telescopic fingers that can unfurl up to 3′ long.',
    ],
    SHADOW: [
        'Edges blur and ripple even when standing still.',
        'Casts no shadow of its own.',
        'Voice is a whisper layered many times over.',
        'Recoils sharply from any sudden light.',
        'Eye-like holes appear and disappear across body.',
        'Very familiar silhouette.',
        'Shifting shades of the night sky.',
        'A mass of worm-like shadows, moving together.',
        'Too many mouths.',
        'Thousands of voices, whispering at once.',
    ],
    'SHAPE-STEALER': [
        'Skin has a faint, unnatural sheen, even in its stolen form.',
        'Pauses a beat too long before answering questions.',
        'Moves with something subtly, indefinably wrong.',
        'Voice carries a faint, wet undertone.',
        'Coughs after speaking adopted name.',
        'Smokes in contact with silver or cold iron.',
        'Cannot cross running water.',
        'One extra finger.',
        'Fizzing cyan blood.',
        'Breath smells of blossom',
    ],
    SKELETON: [
        'Joints click and grind with every movement.',
        'Wears whatever finery it can still fit.',
        'Empty sockets somehow convey clear emotion.',
        'Rattles faintly with each step, bones loose in their sockets.',
        'Flowers fill its ribcage.',
        'Addresses the skeleton inside living people.',
        'False eyes inserted into eye sockets.',
        'Smells of cheap wine.',
        'Wears a wig and make-up.',
        'Host to a rat inside its skull.',
    ],
    'SNAIL, GIANT-MUTANT': [
        'Shell is scarred and pitted with old damage.',
        'Eyestalks swivel independently, tracking separate things.',
        'Leaves a wide, glistening trail in its wake.',
        'Retreats into its shell at the faintest hint of danger.',
        'Pointy, striped shell.',
        'Three eye stalks.',
        'Leaves a trail of fluorescent slime.',
        '1′-wide eyes with dozens of independently mobile pupils.',
        'Multiple rows of snapping teeth.',
        'Jet black, oozing orange slime.',
    ],
    'SNAIL, GIANT-PSIONIC': [
        'Shell swirls with faint, shifting colors.',
        'Eyestalks bear small, disquieting faces.',
        'Radiates a low, droning hum, felt more than heard.',
        'Leaves a shimmering, faintly luminous trail.',
        'Shell glows incandescent green.',
        'Humanoid faces on each of its eye stalks.',
        'Writhing, purple tentacles around mouth.',
        'Golden halo of pulsing, psychic energy.',
        'Sings beautiful, virtuoso operas.',
        'Leaves a trail of evaporating psychedelic ooze.',
    ],
    SPECTRE: [
        'Wears a crown or finery, centuries out of fashion.',
        'Voice carries the weight of old, absolute authority.',
        'Passes through solid stone without a sound.',
        'Trailing wisps curl and reach, as if grasping.',
        'Crown of steel thorns.',
        'Covered in ritualistic scars.',
        'Misty aura of demonic visages.',
        'Wields a great two-handed sword (damage as per touch).',
        'Hands dripping with spectral blood.',
        'Wears a leering skull mask.',
    ],
    SPRITE: [
        'Wings blur into a faint chime when it flies.',
        'Speaks only in rhyming couplets when startled.',
        'Trails a thin ribbon of captured moonlight.',
        'Steals small shiny objects and forgets where it hid them.',
        'Riding a rainbow-hued dragonfly (as a giant fly).',
        'Compound eyes and antennae.',
        'Speech accompanied by twittering giggles.',
        'Naked and hairless.',
        'Lumpy, warty flesh.',
        'Curly horns.',
    ],
    'TALKING ANIMAL': [
        'Speaks with a surprisingly formal, old-fashioned turn of phrase.',
        'Regards travelers with obvious, calculating curiosity.',
        'Poses a riddle before offering any real help.',
        'Otherwise behaves exactly like its mundane kin.',
    ],
    TREOWERE: [
        'Bark-skin is scarred with old axe-wounds, long healed over.',
        'Roots trail from its feet, withering the grass it walks.',
        'Speaks slowly, each word creaking like a bent branch.',
        'Leaves a scattering of dead leaves in its wake, regardless of season.',
        'Infested with spiders and insects.',
        'Sweet scent of apples.',
        'Wrapped in Creeping Prune (Foraging, DCB).',
        'Oozing thick amber sap.',
        'Beard and eyebrows of thick moss.',
        'Entirely stripped of bark.',
    ],
    TROLL: [
        'Skin knits visibly where old wounds have healed wrong.',
        'Smells of wet moss and old blood.',
        'Drags a knuckled club scarred with tooth-marks.',
        'Sniffs the air loudly, tracking by scent.',
        'Bony growths on head, like petrified antler fungus.',
        'Clumsy, three-fingered hands.',
        'Huge, milky eyes and a gawping mouth.',
        'Moss sprouts in its wake, as its feet touch the earth.',
        'Translucent flesh—with thick black bones and organs.',
        'Two heads: one wicked, the other kindly.',
    ],
    'UNICORN-BLESSED': [
        'Coat shimmers faintly, shifting hue with the light.',
        'Hoofprints leave the faintest impression of wildflowers.',
        'Regards mortals with wary, measured dignity.',
        'Horn is faintly warm to the touch.',
        'Regal, goat-like beard.',
        'Voice tinkles like wind chimes.',
        'Shifting aura of rainbow colour.',
        'Hooves fashioned from pearl.',
        'Scent reminiscent of home.',
        'Tail of a lion.',
    ],
    'UNICORN-CORRUPT': [
        'Coat has gone dull, ashen, and faintly damp-looking.',
        'Eyes carry a fixed, malicious gleam.',
        'Horn drips with a faint, dark ichor.',
        'Hoofbeats ring wrong, a half-beat off true.',
        'Cyan froth around the mouth.',
        'Speaks in tongues. Sentences emerge from the babble.',
        'Rippling, violet aura of energy.',
        'Feet end in mutated hooves, cloven into 3 claws.',
        'Empty, bleeding eye sockets. Navigates by magic.',
        'Two mouths, one gnashing, one grinning',
    ],
    WEREWOLF: [
        "Nails are permanently thickened, faintly clawed even in human form.",
        "Eyes catch and reflect light like an animal's.",
        'Restless, prowling energy, even standing still.',
        'Old, half-healed scars mark both forms.',
        'Snow white hair and fur.',
        'Constantly sniffling and snorting.',
        'Blood red eyes.',
        'Uncontrollable giggles, even in wolf form.',
        'Lolling, drooling tongue.',
        'Thick uni-brow in both forms.',
    ],
    'WICKER GIANT': [
        'Woven frame creaks with every heavy step.',
        'A faint green glow flickers deep within its chest.',
        'Trailing vines and dried leaves shed with each movement.',
        'Moves with slow, deliberate, unstoppable purpose.',
        'Wicked, leering grin with thigh-bones for teeth.',
        'Topped with a gigantic pumpkin with carved visage.',
        'Hung with iron owls that clank in the breeze.',
        'Wicker laths bound with cord of silvery elf-hair.',
        'Wheezes eerily as it moves about.',
        'Head festooned with brambles, like hair and beard.',
    ],
    WIGHT: [
        'Grave-wrappings are still faintly visible beneath the flesh.',
        'Eyes burn with a cold, hateful light.',
        'Jewelry and old coin are fused directly into rotting skin.',
        'Moves with the stiff, deliberate gait of the recently risen.',
        'Jaw completely unhinges.',
        'Endlessly repeat corpse’s final words.',
        'Silver coins in eye sockets.',
        'Nearby plants char and wilt.',
        'Adorned in bone trinkets.',
        'Scent of lingering smoke.',
    ],
    WITCH: [
        'Eyes carry an unnatural, otherworldly depth.',
        'Speaks with careful, measured precision.',
        'Adorned with small charms of bone, thread, and herb.',
        'A faint chill follows wherever she walks.',
        'Arms tattooed with winding brambles and knives.',
        'Emaciated and bloodstained.',
        'Enchanting beauty. Face shifts between different forms.',
        'Small bird sits on shoulder, twittering quietly in ear.',
        'Eyes of pure black; otherworldly gaze.',
        'Skin slick with iridescent oil.',
    ],
    'WITCH OWL': [
        'Head rotates further than seems natural.',
        'Eyes hold a fixed, unblinking violet glare.',
        'Feathers seem to drink the surrounding light.',
        'Utterly silent in flight, even at close range.',
        'Single large eye in centre of forehead.',
        'Feathers shimmer, as if bathed in moonlight.',
        'Human mouth, is able to speak.',
        'Haloed with eerie, purple light.',
        'Silver antlers.',
        'Wing-tip feathers made of silver. (12 feathers, 50gp each.)',
    ],

    WODEWOSE: [
        'Matted hair and beard woven through with living ivy.',
        'Moves in complete silence despite its bulk.',
        'Eyes are a flat, mossy green, unblinking.',
        'Carries a gnarled staff taller than itself.',
        'Crawling with beetles.',
        'Shaggy, auburn hair, mane of oak leaves.',
        'Rough, black hair, tangled and braided.',
        'Face covered in fern shoots. Long, pink tongue lolls.',
        'Long, tawny beard, laced with vines.',
        'Staring, bulbous black eyes. Clad entirely in moss.',
    ],


    WOODGRUE: [
        'Bark-textured skin mottled with real lichen.',
        'Fingers taper into twig-like points.',
        'Rustles softly with every movement, like wind through leaves.',
        'Freezes stock-still and near-invisible against tree trunks when alarmed.',
        'Twitchy, wobbly ears.',
        'Purple nose and lips.',
        'Wiry mohawk.',
        'Dressed in dapper tweed, with a monocle.',
        'Chitters with excitement and mirth.',
        'Frilly bonnet.',
    ],
    WRONGUNCLE: [
        'Skin has the faint, waxy sheen of a mushroom cap.',
        'Speaks in half-remembered turns of phrase.',
        "Face keeps drifting toward an expression that isn't quite right.",
        'Carries some small, treasured item from a life not its own.',
        'Sports a dead squirrel, in memory of its former hat.',
        'Face contorts between benign smile and twisted grimace.',
        'Knitted “clothes” of woven mycelia (attached to body).',
        'Wretchedly weeps and sniffles.',
        'Attracts flies, bees, sprites, and small birds.',
        'Two souls in one; switches personalities at intervals.',
    ],
    'WYRM-BLACK BILE': [
        'Trailing slime scorches the grass wherever it pools.',
        'Segmented body ripples in waves rather than crawling.',
        'Breath curdles nearby water black.',
        'Retreats from open flame with a furious hiss.',
        'Reeks of sulphur.',
        'Eyes of phosphorescent amber.',
        'Plume of lustrous, black feathers around the neck.',
        'Thorns along sides.',
        'Salivates and froths at the mouth.',
        'Scales covered with moss.',
    ],
    'WYRM-BLOOD': [
        'Scales run warm to the touch, faintly steaming in cold air.',
        'Face carries an unsettling, almost noble bearing.',
        'Voice is smooth, persuasive, and utterly untrustworthy.',
        'Leaves the ground scorched wherever it rests.',
        'Blood weeps from the eyes of all creatures in its presence.',
        'Antlers decorated with skulls of victims.',
        'Leaves a trail of clotted blood in its wake.',
        'Long, orange beard.',
        'Reeks of carrion.',
        'Two small mouths that speak in unison with the primary.',
    ],
    'WYRM-PHLEGM': [
        'Scales glisten with a permanent, oily sheen.',
        'Moves in slow, hypnotic coils.',
        'Voice is a low, dreamy murmur.',
        'Leaves a faint trail of iridescent slime.',
        'Dazzling scales reflect an unseen light.',
        'Triple-forked, yellow tongue.',
        'Third, violet eye in centre of forehead.',
        'Loves riddles and speaks in rhyme.',
        'Accompanied by the odour of aromatic resins.',
        'Covered in a clear slime.',
    ],
    'WYRM-YELLOW BILE': [
        'Huge, fatty jowls.',
        'Bifurcated tail.',
        'Milky pus, oozing from between the scales.',
        'Lolling, violet tongue.',
        'Dozens of small, white eyes on the cheeks and forehead.',
        'Twisted, black tusks.',
    ],
    YICKERWILL: [
        'Wings and body emit a smouldering smoke.',
        'Long, spiralling tongue folds in and out.',
        'Rows of tiny, insectoid legs along chest.',
        'Eye patterns on wings.',
        'Ruff of iridescent, peacock-like feathers.',
        'Icicles hanging from wings.',
    ],
};

const pick = arr => arr[Math.floor(Math.random() * arr.length)];

// Mounts referenced by the source ("details[...].mounts") point at item tables we
// don't have — these are original short lists standing in for them.
const BREGGLE_MOUNTS = [
    'a shaggy highland pony',
    'a broad-backed goat, its horns capped in brass',
    'an ash-grey mule, unbothered by anything',
    'a warhorse well past its prime',
];
const ELF_MOUNTS = [
    'a fairy horse',
    'a silver-maned fairy horse',
    'a white hart, bridled in woven silver',
    'a fairy horse whose hoofbeats make no sound at all',
];
const FOMORIAN_HERD = [
    'wild boar',
    'shaggy mountain goats',
    'starved wolves, kept more as hounds than beasts',
    'a yoked ox, dragging a broken cart behind it',
];
const FAIRY_HORSE_COMPANIONS = [
    'a young foal, still unsteady on its legs',
    'a second fairy horse, silent and watchful',
    'a hare that never strays far from its hooves',
    'a barn owl riding upon its back',
];

// A handful of "noble" or notable species show up with an escort and/or a mount,
// per the source's hasEntourage/hasMount data. Entourage counts and % chances are
// sourced; the specific mount/herd/companion flavor is original (see lists above).
const ENTOURAGE_DATA = {
    'BREGGLE-LONGHORN': {
        mountChance: 4 / 6,
        mount: () => pick(BREGGLE_MOUNTS),
        entourageChance: 4 / 6,
        entourage: hasLair => {
            const n = rollDice(hasLair ? '4d8' : '1d12');
            const leader = nameForCreature('BREGGLE-SHORTHORN').name;
            return `${n} breggle-shorthorns, led by ${leader}`;
        },
    },
    'DEORLING-DOE': {
        entourageChance: 1,
        entourage: () => `${rollDice('2d6')} fawns`,
    },
    'ELF-COURTIER': {
        mountChance: 3 / 6,
        mount: () => pick(ELF_MOUNTS),
        entourageChance: 4 / 6,
        entourage: () => {
            const nk = rollDice('1d4');
            const knightName = nameForCreature('ELF-KNIGHT').name;
            const servitors = rollDice('2d4');
            const wandererName = nameForCreature('ELF-WANDERER').name;
            return `${nk} elf-knight${nk > 1 ? 's' : ''} (${nk > 1 ? 'led by' : 'named'} ${knightName}), and ${servitors} servitors, led by ${wandererName}`;
        },
    },
    'ELF-KNIGHT': {
        mountChance: 5 / 6,
        mount: () => pick(ELF_MOUNTS),
    },
    'FAIRY HORSE': {
        entourageChance: 3 / 6,
        entourage: () => `accompanied by ${pick(FAIRY_HORSE_COMPANIONS)}`,
    },
    FOMORIAN: {
        entourageChance: 4 / 6,
        entourage: () => `${rollDice('2d4')} ${pick(FOMORIAN_HERD)}`,
    },
    GLOAM: {
        entourageChance: 1 / 6,
        entourage: () => `${rollDice('1d4')} charmed children`,
    },
};

/**
 * Resolve an optional mount and/or entourage for the handful of species that have one.
 * @param {string} creatureName - raw table entry name
 * @param {boolean} hasLair - affects the size of some entourages (e.g. breggle-longhorn)
 * @returns {{ mount: string|null, entourage: string|null }}
 */
export function entourageForCreature(creatureName, hasLair) {
    const key = creatureName.replace(/\s*\([^)]*\)\s*$/, '').trim();
    const data = ENTOURAGE_DATA[key];
    if (!data) return {mount: null, entourage: null};

    return {
        mount: data.mount && Math.random() < data.mountChance ? data.mount() : null,
        entourage: data.entourage && Math.random() < data.entourageChance ? data.entourage(hasLair) : null,
    };
}

function tierForLevel(level) {
    const n = parseInt(level, 10) || 1;
    if (n <= 3) return 'Treasure03';
    if (n <= 7) return 'Treasure46';
    return 'Treasure79';
}

/**
 * Resolve lair/trait/hoard-tier/possession/vulnerability flavor for a wilderness-encounter
 * creature entry.
 * @param {string} creatureName - raw table entry name, e.g. "BARROWBOGEY", "TREOWERE (CHAOTIC)"
 * @param {string|number} [monsterLevel] - the creature's Shadowdark level, used to pick a treasure tier
 * @returns {{ trait: string|null, hasLair: boolean, hoardTier: string|null, possessionTier: string|null, vulnerability: string|null }}
 */
export function loreForCreature(creatureName, monsterLevel) {
    const key = creatureName.replace(/\s*\([^)]*\)\s*$/, '').trim();
    const lairInfo = LAIR_DATA[key];
    const traits = SPECIES_TRAITS[key];
    const hasLair = lairInfo ? Math.random() < lairInfo.lairChance : false;

    return {
        trait: traits ? pick(traits) : null,
        hasLair,
        hoardTier: hasLair && lairInfo?.hasHoard ? tierForLevel(monsterLevel) : null,
        // Possessions are what a creature carries day-to-day, so only relevant when
        // it's out and about, not when we're already describing its lair's hoard.
        possessionTier: !hasLair && lairInfo?.hasPoss ? tierForLevel(monsterLevel) : null,
        vulnerability: WYRM_SPECIES.has(key) ? pick(WYRM_VULNERABILITIES) : null,
    };
}
