// Dolmenwood name pools, adapted from a fan-made Perchance encounter generator
// (kindred first/last names, monster-specific name pools, and group names).

export const KINDRED_NAMES = {
  Breggle: {
    masculine: [
      "Aele",
      "Braembel",
      "Broob",
      "Crump",
      "Drerdl",
      "Frennig",
      "Grerg",
      "Gripe",
      "Llerg",
      "Llrod",
      "Lope",
      "Mashker",
      "Olledg",
      "Rheg",
      "Shadgore",
      "Shadwell",
      "Shadwicke",
      "Shadwick",
      "Shandor",
      "Shank",
      "Snerd",
      "Addle",
      "Andred",
      "Blocke",
      "Clover",
      "Crewwin",
      "Curlip",
      "Eleye",
      "Ellip",
      "Frannidore",
      "Ghrend",
      "Grennigore",
      "Gwendl",
      "Hrannick",
      "Hwoldrup",
      "Lindor",
      "Merrild",
      "Smenthard",
      "Snerg",
      "Wendlow",
      "Windor",
      "Lump",
    ],
    feminine: [
      "Aedel",
      "Berrild",
      "Bredhr",
      "Draed",
      "Fannigrew",
      "Frandorup",
      "Grendilore",
      "Grendl",
      "Grewigg",
      "Hildrup",
      "Hraigl",
      "Hwendl",
      "Maybel",
      "Myrkle",
      "Nannigrew",
      "Pettigrew",
      "Rrhimbr",
      "Shord",
      "Smethra",
      "Wheld",
      "Addle",
      "Andred",
      "Blocke",
      "Clover",
      "Crewwin",
      "Curlip",
      "Eleye",
      "Ellip",
      "Frannidore",
      "Ghrend",
      "Grennigore",
      "Gwendl",
      "Hrannick",
      "Hwoldrup",
      "Lindor",
      "Merrild",
      "Smenthard",
      "Snerg",
      "Wendlow",
      "Windor",
      "Brewigg",
      "Timilda",
      "Nelga",
    ],
    surnames: [
      "Blathergripe",
      "Bluegouge",
      "Bockbrugh",
      "Bockstump",
      "Elbowgen",
      "Forlocke",
      "Hwodlow",
      "Lankshorn",
      "Lockehorn",
      "Longbeard",
      "Longshanks",
      "Shankwold",
      "Smallbuck",
      "Snicklebock",
      "Snidebleat",
      "Snoode",
      "Underbleat",
      "Underbuck",
      "Wolder",
      "Woldleap",
      "Shankwolde",
      "Furroughby",
      "Groghorn",
      "Brumble",
    ],
  },
  Human: {
    masculine: [
      "Arfred",
      "Brom",
      "Bunk",
      "Chydewick",
      "Crump",
      "Dimothy",
      "Guillem",
      "Henrick",
      "Hogrid",
      "Jappser",
      "Joremey",
      "Josprey",
      "Jymes",
      "Mollequip",
      "Rodger",
      "Rogbert",
      "Samwise",
      "Shadwell",
      "Shank",
      "Sidley",
      "Andred",
      "Arda",
      "Aubrey",
      "Clement",
      "Clewyd",
      "Dayle",
      "Gemrand",
      "Hank",
      "Lyren",
      "Maude",
      "Megynne",
      "Moss",
      "Robyn",
      "Rowan",
      "Sage",
      "Tamrin",
      "Ursequine",
      "Waldra",
      "Waydred",
      "Wendlow",
      "Nedwynne",
      "Lowlan",
      "Pike",
      "Sylvain",
      "Arbie",
      "Ingram",
      "Merriman",
      "Hadle",
      "Edwynne",
      "Ogham",
      "Lyren",
      "Brigg",
      "Edgar",
      "Emeritus",
      "Bagsley",
      "Eggwin",
      "Sydewich",
      "Reynold",
      "Benedict",
      "Broobe",
      "Primulus",
      "Smyde",
      "Ignatius",
      "Hoagle",
      "Simwise",
      "Heggid",
      "Sprewdiman",
      "Austache",
      "Blino",
      "Hagbard",
      "Jock",
      "Tasper",
      "Mannog",
      "Gherigrew",
      "Alfolonious",
      "Sedgewick",
      "Arb",
      "Bilbry",
      "Willy",
      "Mollish",
      "Bartholomew",
      "Hallyd",
      "Duncan",
      "Wiston",
      "Johannis",
      "Henricus",
      "Chade",
      "Elm",
      "Frewdric",
      "Hodge",
      "Abram",
      "Bilbro",
      "Boren",
      "Arne",
      "Basil",
      "Baxton",
      "Bennett",
      "Bertram",
      "Clovis",
      "Conrad",
      "Cyrus",
      "Denis",
      "Finn",
      "Hannibal",
      "Jeremiah",
      "Johan",
      "Lothar",
      "Lucian",
      "Merrick",
      "Milo",
      "Ogden",
      "Quentin",
      "Rufus",
      "Silas",
      "Torsten",
      "Tristan",
      "Warrick",
      "Webster",
      "Rex",
      "Thaddeus",
      "Abthius",
      "Albrith",
      "Brannock",
      "Dunstan",
      "Eggort",
      "Foggarty",
      "Gondyw",
      "Halredd",
      "Harwin",
      "Humbert",
      "Lunt",
      "Mawkin",
      "Merewald",
      "Osric",
      "Quister",
      "Swithin",
      "Vinicus",
      "Wattle",
      "Whittery",
      "Wilmot",
      "Bastle",
      "Beowan",
      "Birch",
      "Coppin",
      "Joryn",
      "Lynden",
      "Orris",
      "Poole",
      "Vale",
      "Waylaine",
      "Willofrith",
      "Triswick",
    ],
    feminine: [
      "Agnel",
      "Amonie",
      "Celenia",
      "Emelda",
      "Gertwinne",
      "Gilly",
      "Gretchen",
      "Gwendolyne",
      "Hilda",
      "Illabell",
      "Katerynne",
      "Lillibeth",
      "Lillith",
      "Lisabeth",
      "Mabel",
      "Maydrid",
      "Melysse",
      "Molly",
      "Pansy",
      "Roese",
      "Andred",
      "Arda",
      "Aubrey",
      "Clement",
      "Clewyd",
      "Dayle",
      "Gemrand",
      "Hank",
      "Lyren",
      "Maude",
      "Megynne",
      "Moss",
      "Robyn",
      "Rowan",
      "Sage",
      "Tamrin",
      "Ursequine",
      "Waldra",
      "Waydred",
      "Wendlow",
      "Bronywyn",
      "Sadewyn",
      "Gilly-Ann",
      "Hanctra",
      "Tamrin",
      "Shandra",
      "Heremine",
      "Ayla",
      "Wiglow",
      "Griselda",
      "Sandrine",
      "Adreline",
      "Farnham",
      "Margerie",
      "Nancy",
      "Lorrima",
      "Mogget",
      "Daphne",
      "Algenon",
      "Aspith",
      "Hague",
      "Liane",
      "Sespettra",
      "Megwynne",
      "Aegnyth",
      "Ellery",
      "Mercy",
      "Carrington",
      "Amande",
      "Berrit",
      "Merridwyn",
      "Jesibelle",
      "Zoemina",
      "Wilfrinda",
      "Bertha",
      "Hilda",
      "Gemyme",
      "Senna",
      "Grent",
      "Grottle",
      "Gilda",
      "Matilda",
      "Marge",
      "Kerth",
      "Gylynda",
      "Emma",
      "Anna",
      "Abigail",
      "Alva",
      "Alma",
      "Astrid",
      "Beatrix",
      "Bianca",
      "Brunhilde",
      "Ella",
      "Elsbeth",
      "Esme",
      "Fiora",
      "Gertrude",
      "Hester",
      "Iris",
      "Jilly",
      "Margot",
      "Marian",
      "Marigold",
      "Olga",
      "Pepper",
      "Phoebe",
      "Poppy",
      "Rose",
      "Sigrid",
      "Ursula",
      "Wendy",
      "Willow",
      "Winifred",
      "Yvette",
      "Zora",
      "Alyss",
      "Anest",
      "Benestra",
      "Briselle",
      "Everilde",
      "Edwisse",
      "Elditha",
      "Godwynne",
      "Hildrith",
      "Hollyhock",
      "Maerwinna",
      "Magritte",
      "Osredda",
      "Primula",
      "Roswyn",
      "Sibbelee",
      "Thessabel",
      "Wendreth",
      "Wrenley",
      "Beowan",
      "Denby",
      "Eoda",
      "Gylden",
      "Haemma",
      "Merren",
      "Osrin",
      "Tamrand",
      "Triswick",
      "Vale",
    ],
    surnames: [
      "Addercapper",
      "Burl",
      "Candleswick",
      "Crumwaller",
      "Dogoode",
      "Dregger",
      "Dunwallow",
      "Fraggleton",
      "Gruewater",
      "Harper",
      "Lank",
      "Logueweave",
      "Loomer",
      "Malksmilk",
      "Smith",
      "Sunderman",
      "Swinney",
      "Tolmen",
      "Weavilman",
      "Wolder",
      "Baldricke",
      "Hargle",
      "Creede",
      "Gallbucket",
      "Pickfoot",
      "Aster",
      "Snyde",
      "Bertil",
      "Locke",
      "Bogle",
      "Underhill",
      "Butterwheeve",
      "Woglemain",
      "Waldefroum",
      "Hogbeard",
      "Tweede",
      "Shodgerey",
      "Hadlewreath",
      "Crump",
      "Meagre",
      "Bogleman",
      "Drabe",
      "Corundum",
      "Sumner",
      "Dobey",
      "Ribblemead",
      "Stallowmade",
      "Whilpston",
      "Maldwort",
      "Barhaim",
      "Redhearth",
      "Delora",
      "Paste",
      "Gravesby",
      "Crookbone",
      "Grump",
      "Hedger",
      "Drouge",
      "Ogsbody",
      "Humblebuff",
      "Craphand",
      "Broadmain",
      "Hogwash",
      "Axminster",
      "Brandybile",
      "Jerricorn",
      "Hydball",
      "Kneeve",
      "Smunk",
      "Marrowbold",
      "Furngle",
      "Horsely",
      "Brancher",
      "Tew",
      "Cormick",
      "Lumley",
      "Crymehump",
      "Shydewick",
      "Alquip",
      "Murderman",
      "Thorncripe",
      "Heape",
      "Margleman",
      "Chudrow",
      "Ulmer",
      "Worms",
      "Hodgeheg",
      "Nag",
      "Bucksnort",
      "Ongledrome",
      "Hangman",
      "Ladle",
      "Parr",
      "Grange",
      "Blore",
      "Koop",
      "Goodwife",
      "Merryweather",
      "Vague",
      "Bregson",
      "Buttons",
      "Chunkwell",
      "Goodwine",
      "Chandler",
      "Mumsalot",
      "Jobsworth",
      "Goodenough",
      "Calamite",
      "Heathrough",
      "Wondred",
      "Macell",
      "Longworth",
      "Wight",
      "Loom",
      "Proster",
      "Mirrowyn",
      "Chafely",
      "Hobwill",
      "Shackwine",
      "Dingley",
      "Capulus",
      "Quibbleton",
      "Shrubwick",
      "Lullingford",
      "Jacobus",
      "Ledger",
      "Andor",
      "Grayneforth",
      "Eggfast",
      "Brigford",
      "Rensfred",
      "Purslough",
      "Longwall",
      "Rosny",
      "Sandhollow",
      "Appleby",
      "Bogsmeeve",
      "Bothell",
      "Briddlecombe",
      "Clyde",
      "Cragmere",
      "Crumby",
      "Dreggins",
      "Dunwether",
      "Featherwode",
      "Grubwallow",
      "Hatchcombe",
      "Mucklebloom",
      "Mumpson",
      "Rudkin",
      "Snipeley",
      "Snudgewick",
      "Stokely",
      "Struthermire",
      "Talloway",
      "Wilmotte",
    ],
  },
  Mossling: {
    masculine: [
      "Dombo",
      "Gobd",
      "Gobulom",
      "Golobd",
      "Gremo",
      "Gwomotom",
      "Hollogowl",
      "Kabob",
      "Kollobom",
      "Limbly",
      "Loblow",
      "Mobdemold",
      "Nyoma",
      "Obolm",
      "Oglom",
      "Omb",
      "Shmold",
      "Slumbred",
      "Umbertop",
      "Wobobold",
      "Bendiom",
      "Blobul",
      "Ebdwol",
      "Glob",
      "Gombly",
      "Greblim",
      "Gwoodwom",
      "Hollb",
      "Klolb",
      "Kwolotomb",
      "Lambop",
      "Morromb",
      "Mwoomb",
      "Olob",
      "Oobl",
      "Shlurbel",
      "Smodron",
      "Tomdown",
      "Tomumbolo",
      "Worrib",
    ],
    feminine: [
      "Bilibom",
      "Brimbul",
      "Ebbli",
      "Ghibli",
      "Gobbli",
      "Gwedim",
      "Higwold",
      "Ibulold",
      "Imbwi",
      "Klibli",
      "Klimbim",
      "Libib",
      "Limimb",
      "Marib",
      "Milik",
      "Shlirimi",
      "Shobd",
      "Skimbim",
      "Slimpk",
      "Smodri",
      "Bendiom",
      "Blobul",
      "Ebdwol",
      "Glob",
      "Gombly",
      "Greblim",
      "Gwoodwom",
      "Hollb",
      "Klolb",
      "Kwolotomb",
      "Lambop",
      "Morromb",
      "Mwoomb",
      "Olob",
      "Oobl",
      "Shlurbel",
      "Smodron",
      "Tomdown",
      "Tomumbolo",
      "Worrib",
    ],
    surnames: [
      "Barkhop",
      "Conker",
      "Danklow",
      "Fernhead",
      "Frother",
      "Grimehump",
      "Hogscap",
      "Mossbeard",
      "Mossfurrow",
      "Mould",
      "Mouldfinger",
      "Mudfoot",
      "Mugfoam",
      "Mulchwump",
      "Mushrump",
      "Oddpolyp",
      "Puffhelm",
      "Smallcheese",
      "Sodwallow",
      "Twiggler",
    ],
  },
  Woodgrue: {
    masculine: [
      "Bagnack",
      "Barmcudgel",
      "Bloomfext",
      "Bunglebone",
      "Capratt",
      "Chimm",
      "Delgodand",
      "Drunker",
      "Eortban",
      "Grunkle",
      "Gubber",
      "Gumroot",
      "Gunkuss",
      "Kungus",
      "Longtittle",
      "Lubbal",
      "Olpipes",
      "Runkelgate",
      "Weepooze",
      "Wumpus",
      "Bogfrink",
      "Bongwretch",
      "Chunder",
      "Danklob",
      "Frondbong",
      "Gobblebag",
      "Hootbra",
      "Longsnipe",
      "Lumpfrisk",
      "Mabmungle",
      "Mungus",
      "Obblehob",
      "Oddler",
      "Oodler",
      "Pipplepoke",
      "Slovend",
      "Umple",
      "Unclord",
      "Undermap",
      "Whoopla",
    ],
    feminine: [
      "Bishga",
      "Canaghoop",
      "Cheruffue",
      "Doola",
      "Frogfyrr",
      "Gruecalle",
      "Hoolbootes",
      "Maulspoorer",
      "Mogsmote",
      "Molemoch",
      "Moonmilk",
      "Munmun",
      "Nettaclare",
      "Oorcha",
      "Palliepalm",
      "Pimplepook",
      "Puggump",
      "Rolliepolk",
      "Sasserpipe",
      "Whipsee",
      "Bogfrink",
      "Bongwretch",
      "Chunder",
      "Danklob",
      "Frondbong",
      "Gobblebag",
      "Hootbra",
      "Longsnipe",
      "Lumpfrisk",
      "Mabmungle",
      "Mungus",
      "Obblehob",
      "Oddler",
      "Oodler",
      "Pipplepoke",
      "Slovend",
      "Umple",
      "Unclord",
      "Undermap",
      "Whoopla",
      "Blinghop",
      "Threeble",
    ],
    surnames: [
      "Bobbleslime",
      "Bogbabble",
      "Bootswap",
      "Chumley",
      "Cobwallop",
      "Drooglight",
      "Dungobble",
      "Eggmumble",
      "Hogslapper",
      "Hortleswoop",
      "Hungerslip",
      "Lankwobble",
      "Moorsnob",
      "Mundersnog",
      "Pencecrump",
      "Persnickle",
      "Shunderbog",
      "Snodgrass",
      "Wallerbog",
      "Woodfuffle",
      "Pidderpat",
    ],
  },
  Crookhorn: {
    masculine: [
      "Bart",
      "Billy",
      "Broo",
      "Broob",
      "Curlip",
      "Grim",
      "Grip",
      "Gripe",
      "Hoge",
      "Lank",
      "Lope",
      "Lurp",
      "Org",
      "Shadgore",
      "Shank",
      "Slurp",
      "Snerd",
      "Snerg",
      "Willy",
      "Winder",
      "Addle",
      "Adder",
      "Blocke",
      "Bog",
      "Cleaver",
      "Crewn",
      "Curlip",
      "Dunder",
      "Frand",
      "Grerg",
      "Grin",
      "Gore",
      "Hanck",
      "Hod",
      "Lin",
      "Meg",
      "Mug",
      "Shrug",
      "Sodlow",
      "Wug",
      "Bert",
      "Grobnott",
    ],
    feminine: [
      "Breek",
      "Crag",
      "Crewn",
      "Dank",
      "Errid",
      "Fanny",
      "Grewigg",
      "Gruw",
      "Lankly",
      "Nagly",
      "Nanna",
      "Plim",
      "Prim",
      "Scrag",
      "Shim",
      "Shoddy",
      "Slyme",
      "Slynn",
      "Smoo",
      "Wilda",
      "Addle",
      "Adder",
      "Blocke",
      "Bog",
      "Cleaver",
      "Crewn",
      "Curlip",
      "Dunder",
      "Frand",
      "Grerg",
      "Grin",
      "Gore",
      "Hanck",
      "Hod",
      "Lin",
      "Meg",
      "Mug",
      "Shrug",
      "Sodlow",
      "Wug",
      "Briggsy",
      "Scruff",
      "Grerta",
      "Drogba",
    ],
    surnames: [
      "Bludger",
      "Boner",
      "Bugber",
      "Clubber",
      "Crapshod",
      "Gouger",
      "Grimes",
      "Hogbard",
      "Hogblood",
      "Hoglick",
      "Limplore",
      "Nagger",
      "Nailer",
      "Quimmer",
      "Shergulp",
      "Shiver",
      "Smollow",
      "Sodder",
      "Wallow",
      "Wanklore",
      "Gobshyte",
    ],
  },
  Drune: {
    masculine: [
      "Abam",
      "Aestgrym",
      "Brackborne",
      "Brimgord",
      "Cantcor",
      "Celleddach",
      "Dhrimmlon",
      "Forroth",
      "Grimlocke",
      "Hecator",
      "Hestith",
      "Hestobraithe",
      "Illforridh",
      "Majorus",
      "Malrubius",
      "Mirroddor",
      "Molloch",
      "Mordoch",
      "Oglimoth",
      "Waykehald",
      "Agred",
      "Ambe",
      "Athe",
      "Eld",
      "Frig",
      "Gremd",
      "Haldrime",
      "Hancith",
      "Hestor",
      "Jhaellen",
      "Jhorhen",
      "Limnis",
      "Lolldhrimm",
      "Mandra",
      "Mirrod",
      "Morda",
      "Oblith",
      "Obwynd",
      "Oed",
      "Wakehyld",
      "Tharvok",
      "Zorduin",
      "Braegoth",
      "Malchreth",
      "Krymor",
    ],
    feminine: [
      "Aembgyth",
      "Andramath",
      "Braithlynne",
      "Caendrgald",
      "Deregbra",
      "Eolenn",
      "Eostra",
      "Estembra",
      "Frigdra",
      "Glana",
      "Gremlith",
      "Gwentmarg",
      "Gwordlith",
      "Haelleth",
      "Idralynne",
      "Lagwynne",
      "Lestwith",
      "Polldra",
      "Pollith",
      "Sigdra",
      "Agred",
      "Ambe",
      "Athe",
      "Eld",
      "Frig",
      "Gremd",
      "Haldrime",
      "Hancith",
      "Hestor",
      "Jhaellen",
      "Jhorhen",
      "Limnis",
      "Lolldhrimm",
      "Mandra",
      "Mirrod",
      "Morda",
      "Oblith",
      "Obwynd",
      "Oed",
      "Wakehyld",
    ],
    surnames: [
      "Astraleth",
      "Bonewort",
      "Broodmoot",
      "Broomewith",
      "Canker",
      "Casket",
      "Chancter",
      "Dolmward",
      "Doome",
      "Duskwith",
      "Hallow",
      "Loome",
      "Moonewer",
      "Owlhame",
      "Unction",
      "Unlight",
      "Vaunte",
      "Wicker",
      "Wraithmord",
      "Wyrd",
      "Runeweft",
      "Banehollow",
      "Elderscorn",
      "Wormwight",
      "Shadethorn",
      "Ashlocke",
    ],
  },
  Noble: {
    masculine: [
      "Afton",
      "Albrith",
      "Arthur",
      "Bertrand",
      "Charle",
      "Edwin",
      "Erick",
      "Francois",
      "Gawain",
      "Gondyw",
      "Jospher",
      "Lyredon",
      "Maximillian",
      "Nash",
      "Pieter",
      "Rogbert",
      "Treeve",
      "Trevyn",
      "Uther",
      "Waylord",
      "Adelais",
      "Ance",
      "Blythe",
      "Brandon",
      "Candice",
      "Chynce",
      "Dacre",
      "Darcy",
      "Guillaine",
      "Gwend",
      "Hague",
      "Medigord",
      "Megynne",
      "Melysse",
      "Merrild",
      "Tristam",
      "Ulva",
      "Ursequine",
      "Wynne",
      "Thespian",
      "Sagewine",
      "Walter",
      "Harald",
      "Bastian",
      "Chortle",
      "Hadrian",
      "Lythe",
      "Osquip",
      "Osric",
      "Hoarsent",
      "Sirrop",
      "Tegwyn",
      "Henry",
      "Eldrin",
      "Archibald",
      "Gaspar",
      "Gilbert",
      "Giles",
      "Wolfgang",
      "Oswald",
      "Geoffrey",
      "Guy",
      "Eckhart",
      "Balthazar",
      "Caspian",
      "Erasmus",
      "Florian",
      "Hamlin",
      "Leopold",
      "Leoric",
      "Mortimer",
      "Neville",
      "Orion",
      "Percival",
      "Reinhold",
      "Stratford",
      "Valentin",
    ],
    feminine: [
      "Abygail",
      "Alienor",
      "Amandine",
      "Augustina",
      "Bethany",
      "Emelda",
      "Esther",
      "Grace",
      "Lisabeth",
      "Lucia",
      "Myranda",
      "Olivia",
      "Persephone",
      "Persimone",
      "Primace",
      "Roese",
      "Sortia",
      "Theodora",
      "Therese",
      "Wilhemina",
      "Adelais",
      "Ance",
      "Blythe",
      "Brandon",
      "Candice",
      "Chynce",
      "Dacre",
      "Darcy",
      "Guillaine",
      "Gwend",
      "Hague",
      "Medigord",
      "Megynne",
      "Melysse",
      "Merrild",
      "Tristam",
      "Ulva",
      "Ursequine",
      "Wynne",
      "Ophelia",
      "Theatrice",
      "Violet",
      "Hilda",
      "Pulsephine",
      "Joan",
      "Myrabelle",
      "Chandilore",
      "Lythe",
      "Wilfrinda",
      "Daphnemene",
      "Amonie",
      "June",
      "Sybil",
      "Alicia",
      "Anastasia",
      "Anika",
      "Cecilia",
      "Charlotte",
      "Constance",
      "Colette",
      "Guinevere",
      "Henrietta",
      "Heloise",
      "Imogene",
      "Isolde",
      "Melisande",
      "Minerva",
      "Odette",
      "Portia",
      "Tabitha",
    ],
    surnames: [
      "Albrime",
      "Baldericke",
      "Brackenwold",
      "Elfwit",
      "Flechette",
      "Guillefer",
      "Haeroth",
      "Harrowmoor",
      "Highgrime",
      "Hogwarsh",
      "Ladrigham",
      "Mulbreck",
      "Nodlock",
      "Offcester",
      "Snape",
      "Symeswitt",
      "Twinsor",
      "Underlow",
      "Waldermost",
      "Woldeleigh",
      "Ablewright",
      "Sanguine",
      "Monocleese",
      "Hazelmire",
      "Waverly",
      "Borrid",
      "Helmwhit",
    ],
  },
  Longhorn: {
    masculine: [
      "Amshred",
      "Craglow",
      "Eriggwen",
      "Fennig",
      "Frannidore",
      "Ghrend",
      "Gryphius",
      "Gwellith",
      "Hgrlleld",
      "Hmardrus",
      "Hwardlow",
      "Hwoldwen",
      "Llandred",
      "Maindr",
      "Nodlore",
      "Olligore",
      "Shadgore",
      "Smerigore",
      "Snide",
      "Wllannoth",
      "Aegll",
      "Andred",
      "Bllennith",
      "Crewwin",
      "Drangwen",
      "Grennigore",
      "Gwendl",
      "Hgwennith",
      "Hmenidore",
      "Hwandilore",
      "Llaind",
      "Merrild",
      "Pllandred",
      "Pwenth",
      "Shennithold",
      "Smenthard",
      "Snerg",
      "Thannidreth",
      "Wendlow",
      "Windor",
      "Simeone",
      "Garnack",
      "Windore",
      "Tekwell",
    ],
    feminine: [
      "Aedel",
      "Berryld",
      "Bethla",
      "Crandragrew",
      "Dweldra",
      "Fannigrew",
      "Fredreth",
      "Grendilore",
      "Hlleth",
      "Howand",
      "Hraigl",
      "Hrannilde",
      "Lindra",
      "Llemberith",
      "Llemmeth",
      "Mmereth",
      "Mregginor",
      "Pettigrew",
      "Pwettig",
      "Wendilore",
      "Aegll",
      "Andred",
      "Bllennith",
      "Crewwin",
      "Drangwen",
      "Grennigore",
      "Gwendl",
      "Hgwennith",
      "Hmenidore",
      "Hwandilore",
      "Llaind",
      "Merrild",
      "Pllandred",
      "Pwenth",
      "Shennithold",
      "Smenthard",
      "Snerg",
      "Thannidreth",
      "Wendlow",
      "Windor",
      "Cabruc",
    ],
    surnames: [
      "Barbicant",
      "Canticreed",
      "Cllern",
      "Cornicus",
      "Furroughby",
      "Hoblewort",
      "Houndswort",
      "Hraiglent",
      "Llhraigl",
      "Lockehorn",
      "Lockelope",
      "Malbleat",
      "Murkin",
      "Overlocke",
      "Pellicorn",
      "Ramius",
      "Shankhollow",
      "Snidebleat",
      "Wealdleap",
      "Wealdlore",
    ],
  },
  Elf: {
    flat: [
      "Bucket-and-Broth",
      "Candle-Bent-Sidewise",
      "Glance-Askew-Guillem",
      "Jack-of-Many-Colours",
      "Lace-and-Polkadot",
      "Lament-of-Bones-Broken",
      "Lightly-Come-Softly",
      "Lillies-o'er-Heartsight",
      "Prick-of-the-Nail",
      "Silver-and-Quicksilver",
      "Spring-to-the-Queen",
      "Sprue-Upon-Gallows",
      "Sun's-Turning-Tide",
      "Supper-Before-Noon",
      "Too-Soon-Begotten",
      "Trick-of-the-Light",
      "Tryst-about-Town",
      "Tumble-and-Thimble",
      "Wine-By-The-Goblet",
      "Youth-Turned-Curdled",
      "Begets-Only-Dreams",
      "Breath-Upon-Candlelight",
      "Chalice-of-Duskviolet",
      "Dream-of-Remembrance",
      "Gleanings-of-Lost-Days",
      "Hands-Bound-By-Crows",
      "Impudence-Hath-Victory",
      "Indigo-and-Patchwork",
      "Marry-No-Man",
      "Morning's-Last-Mists",
      "Murder-of-Ravens",
      "Quavering-of-Night",
      "Revenge's-Sweet-Scent",
      "Seven-Steps-At-Dawn",
      "Shade-of-Winter-Betrayal",
      "Shallow-Pained-Plight",
      "Shallow-Spirit's-Lament",
      "Slips-Behind-Shadows",
      "Spring-Noon's-Arrogance",
      "Violet-and-Clementine",
    ],
  },
  FrostElf: {
    flat: [
      "Bearded-With-Rime",
      "Blackened-and-Bitter",
      "Blood-on-the-Lip",
      "Churned-and-Curdled",
      "Cold-Stroke-of-Midnight",
      "Flurry-and-Fleet",
      "Frosted-Night's-Breath",
      "Hawthorn-and-Thistledown",
      "Mantle-of-Snowdrifts",
      "Plum-Frost-and-Medlars",
      "Raven's-Cold-Call",
      "Shivers-Entwined",
      "Stark-Raving-Sorrow",
      "Stars'-Breath-Splintered",
      "Sunbeam's-Last-Breath",
      "Thankless-and-Spry",
      "Thaw-Never-Comes",
      "Time's-Slow-Ague",
      "Tip-of-the-Hat",
      "Woken-too-Early",
      "Bitter-Dusk's-Hallow",
      "Black-Rime-and-Frostbite",
      "Candle's-Last-Gasp",
      "Dawn's-Feeble-Gleaming",
      "Frost-Dust-Shadow",
      "Frosted-and-Flawless",
      "Frozen-in-Lace",
      "Heart-of-Ice",
      "Hearth's-Bitter-Gloaming",
      "Howling-Wind's-Waltz",
      "Ice-Cap-and-Fox-Gown",
      "Never-Be-Borrowed",
      "Shards-of-Dusk-Mirror",
      "Sleet-Under-Foot",
      "Snowfall-at-Dusk",
      "Splendour-and-Morrow",
      "Spring's-Wilting-of-Heart",
      "Twine-for-the-May-Ball",
      "Weeps-Until-Morning",
      "Willow's-Slow-Freezing",
      "Silver-So-Mirrored",
      "Dawn-Never-Blooms",
      "Slumber-Bone",
      "Whisper-of-Candlelight",
      "Famine-Whistles-Whither",
    ],
  },
  Grimalkin: {
    flat: [
      "Boots",
      "Fripple",
      "Ginger",
      "{Jack|Jill}",
      "Jaspy",
      "Jasqueline",
      "Kitty",
      "Little",
      "{Lord|Lady}",
      "Mogget",
      "Moggle",
      "{Monsieur|Madame}",
      "Nibbles",
      "Penny",
      "Poppet",
      "{Prince|Princess}",
      "Prissy",
      "Tippsy",
      "Tomkin",
      "Toppsy",
      "Whimsly",
      "Dandy",
    ],
    surnames: [
      "Bobblewhisk",
      "Cottonsocks",
      "Flip-a-tail",
      "Flippancy",
      "Fluff-a-kin",
      "Grimalgrime",
      "Grinser",
      "Lickling",
      "Milktongue",
      "Mogglin",
      "Poppletail",
      "Pouncemouse",
      "Pusskin",
      "Ratbane",
      "Snuffle",
      "Tailwhisk",
      "Tippler",
      "Whippletongue",
      "Whipsy",
      "Whiskers",
      "Bobblefrock",
      "Prisslewhiff",
      "Longtail",
    ],
  },
};

// Single-word name pools for named monsters/leaders, keyed by normalized species key
// (see normalizeSpeciesKey below).
export const MONSTER_NAMES = {
  barrowbogey: [
      "Fiddlethumb",
      "Hob",
      "Jack-a-Napes",
      "Nob",
      "Tom-a-Merry",
      "Willbegone",
    ],
  boggin: [
      "Drregl",
      "Gorgrrgl",
      "Hodgellgr",
      "Lrrkrodge",
      "Rredgrelg",
      "Slrrgrelp",
    ],
  centaur_bestial: [
      "Burlgarsh",
      "Dingrab",
      "Dregbor",
      "Grogbor",
      "Sklord",
      "Umbrogd",
    ],
  centaur_sylvan: [
      "Houyhnhnm",
      "Llhwn",
      "Nnhooun",
      "Ouhllwoun",
      "Whynloul",
      "Wwlolyn",
    ],
  cobbin: [
      "Dingle",
      "Dob",
      "Merry",
      "Nuncle",
      "Timble",
      "Umber",
    ],
  crystaloid: [
      "Eemhleem",
      "Hloonwoon",
      "Jreen",
      "Shormooloon",
      "Shwoon",
      "Wimmer",
    ],
  deorling_doe: [
      "Brewhendre",
      "Celiwhend",
      "Hundra",
      "Louhlawi",
      "Huwendre",
      "Wohaa",
    ],
  deorling_stag: [
      "Awawol",
      "Boghan",
      "Ghandre",
      "Hoolourd",
      "Mendre",
      "Wheleg",
    ],
  fairy_horse: [
      "Chancey",
      "Farwain",
      "Frouhaha",
      "Underneigh",
      "Whickerlost",
      "Whinnylord",
    ],
  fomorian: [
      "Aamigor",
      "Dweldge",
      "Malbolge",
      "Phalythryst",
      "Sobdor",
      "Zanzimorg",
    ],
  gargoyle: [
      "Abthius",
      "Aeynid",
      "Albert",
      "Albrith",
      "Apoplect",
      "Baldric",
      "Benester",
      "Bethany",
      "Calafredus",
      "Cantius",
      "Capernott",
      "Choad",
      "Clewyd",
      "Clister",
      "Clyde",
      "Clyve",
      "Cornice",
      "Craven",
      "Dank",
      "Dextre",
      "Dillage",
      "Dougan",
      "Dullard",
      "Egbert",
      "Eggort",
      "Elephantine",
      "Elsa",
      "Esther",
      "Faxis",
      "Flatius",
      "Foggarty",
      "Fredulus",
      "Galaunt",
      "Gawain",
      "Godfrey",
      "Gondyw",
      "Goodenough",
      "Gretchen",
      "Gripe",
      "Gwigh",
      "Habicus",
      "Hamfast",
      "Hildace",
      "Hoargrime",
      "Hodwich",
      "Hollyhock",
      "Horace",
      "Howarth",
      "Howdych",
      "Ingrid",
      "Joane",
      "Jorrael",
      "Jubilant",
      "Keye",
      "Knock",
      "Lillibeth",
      "Loame",
      "Lummox",
      "Maternis",
      "Medigor",
      "Moribund",
      "Neblit",
      "Nuncy",
      "Offrid",
      "Pannard",
      "Pastery",
      "Philodeus",
      "Pious",
      "Poltry",
      "Ponch",
      "Primace",
      "Primula",
      "Puriphon",
      "Quister",
      "Rhilma",
      "Sabian",
      "Sanguine",
      "Sedge",
      "Shank",
      "Signis",
      "Simone",
      "Sortia",
      "Talambeth",
      "Therese",
      "Thorm",
      "Thridgold",
      "Torphia",
      "Tumbel",
      "Vinicus",
      "Visyg",
      "Waylaine",
      "Waylord",
      "Whittery",
      "Wick",
      "Wilbranch",
      "Willibart",
      "Willofrith",
      "Woad",
      "Wort",
      "Wynne",
    ],
  ghoul: [
      "Grast",
      "Gretch",
      "Grime",
      "Grip",
      "Groan",
      "Grunder",
    ],
  gloam: [
      "Carrionette",
      "Hollowbone",
      "Lankwing",
      "Mister Twist",
      "Sawbone",
      "Thinwhistle",
    ],
  goblin: [
      "Bringle-Brangle",
      "Grimble-Grot",
      "Hither-Tither",
      "Idle-Down",
      "Moon-Mumble",
      "Scampalot",
    ],
  harpy: [
      "{Madame|Mother} Cawblood",
      "{Madame|Mother} Crookbone",
      "{Madame|Mother} Lankfeather",
      "{Madame|Mother} Nunclebone",
      "{Madame|Mother} Shinnylop",
      "{Madame|Mother} Thornclaw",
    ],
  harridan: [
      "Agnes",
      "Griseld",
      "Hazel",
      "Meg",
      "Misery",
      "Nanna",
    ],
  jack_o_lantern: [
      "Bogglezoord",
      "Oogyamord",
      "Phroude",
      "Undra",
      "Wymog",
      "Yagzog",
    ],
  madtom: [
      "Fisk",
      "Frond",
      "Grulp",
      "Shlulp",
      "Whelp",
      "Whisk",
    ],
  manticore: [
      "Albert",
      "Cadorphage",
      "Muggle",
      "Nygel",
      "Phrindalorb",
      "Wizen",
    ],
  merfaun: [
      "Aurion",
      "Caprelle",
      "Cornelius",
      "Galethorn",
      "Mystanor",
      "Trystus",
    ],
  mogglewomp: [
      "Boggle",
      "Brungle",
      "Grewl",
      "Mogget",
      "Mowl",
      "Preen",
    ],
  nutcap: [
      "Chrreep",
      "Eergree",
      "Gleereek",
      "Kweelee",
      "Leegreeleek",
      "Rreekreek",
    ],
  pook_morel: [
      "Addercap",
      "Bramble",
      "Cobble",
      "Fiddle",
      "Pippin",
      "Thwist",
    ],
  redcap: [
      "Jack o' Boots",
      "Old Henry",
      "Nicklethumb",
      "Shirtshank",
      "Thimblefiddle",
      "Vex",
    ],
  scarecrow: [
      "Hobnobble",
      "Ramble-Rumble",
      "Stalk",
      "Strider",
      "Tumbleweed",
      "Worzel",
    ],
  scrabey: [
      "Abrinnid",
      "Chantiloppe",
      "Dreebe",
      "Quillit",
      "Sanctwill",
      "Sedgewine",
    ],
  snail_giant_psionic: [
      "Bellowcaulk",
      "Conchwend",
      "Hypnos",
      "Lore",
      "Phelpwind",
      "Sanctalot",
      "Luminescence",
      "Aurabloom",
      "Mindspiral",
      "Dreamwhelm",
      "Ethershell",
      "Psychovoid",
    ],
  spectre: [
      "Agune",
      "Boroth",
      "Ethex",
      "Gruwth",
      "Lirathil",
      "Theune",
    ],
  sprite: [
      "Grick",
      "Gwillick",
      "Jond",
      "Sneeple",
      "Squirkle",
      "Zeep",
    ],
  talking_animal: [
      "Bob",
      "Nibble",
      "Numble",
      "Pip",
      "Scamp",
      "Twitch",
    ],
  treowere: [
      "Burlgrurl",
      "Grumblebole",
      "Limbletroot",
      "Murmlemoot",
      "Rootmoot",
      "Trumblegrum",
    ],
  troll: [
      "Frondhelm",
      "Grudge",
      "Mawb",
      "Skulp",
      "Under",
      "Wheeze",
    ],
  unicorn_blessed: [
      "Abthius",
      "Aeynid",
      "Albert",
      "Albrith",
      "Apoplect",
      "Baldric",
      "Benester",
      "Bethany",
      "Calafredus",
      "Cantius",
      "Capernott",
      "Choad",
      "Clewyd",
      "Clister",
      "Clyde",
      "Clyve",
      "Cornice",
      "Craven",
      "Dank",
      "Dextre",
      "Dillage",
      "Dougan",
      "Dullard",
      "Egbert",
      "Eggort",
      "Elephantine",
      "Elsa",
      "Esther",
      "Faxis",
      "Flatius",
      "Foggarty",
      "Fredulus",
      "Galaunt",
      "Gawain",
      "Godfrey",
      "Gondyw",
      "Goodenough",
      "Gretchen",
      "Gripe",
      "Gwigh",
      "Habicus",
      "Hamfast",
      "Hildace",
      "Hoargrime",
      "Hodwich",
      "Hollyhock",
      "Horace",
      "Howarth",
      "Howdych",
      "Ingrid",
      "Joane",
      "Jorrael",
      "Jubilant",
      "Keye",
      "Knock",
      "Lillibeth",
      "Loame",
      "Lummox",
      "Maternis",
      "Medigor",
      "Moribund",
      "Neblit",
      "Nuncy",
      "Offrid",
      "Pannard",
      "Pastery",
      "Philodeus",
      "Pious",
      "Poltry",
      "Ponch",
      "Primace",
      "Primula",
      "Puriphon",
      "Quister",
      "Rhilma",
      "Sabian",
      "Sanguine",
      "Sedge",
      "Shank",
      "Signis",
      "Simone",
      "Sortia",
      "Talambeth",
      "Therese",
      "Thorm",
      "Thridgold",
      "Torphia",
      "Tumbel",
      "Vinicus",
      "Visyg",
      "Waylaine",
      "Waylord",
      "Whittery",
      "Wick",
      "Wilbranch",
      "Willibart",
      "Willofrith",
      "Woad",
      "Wort",
      "Wynne",
    ],
  unicorn_corrupt: [
      "Craven",
      "Dank",
      "Gripe",
      "Hoargrime",
      "Moribund",
      "Shank",
    ],
  wodewose: [
      "Braghwoole",
      "Hwoon",
      "Mhewood",
      "Omdoobra",
      "Phroon",
      "Umhwoole",
    ],
  wyrm_black_bile: [
      "Bharhgda",
      "Chollep",
      "Frigda",
      "Granegund",
      "Grond",
      "Whelg",
    ],
  wyrm_blood: [
      "Hale",
      "Inctra",
      "Lallandra",
      "Shelm",
      "Speculord",
      "Zmeed",
    ],
  wyrm_phlegm: [
      "Aelethynde",
      "Lemmelde",
      "Mensendra",
      "Sowynder",
      "Undraleeth",
      "Welthrende",
    ],
  wyrm_yellow_bile: [
      "Angraweal",
      "Athemandel",
      "Brimlord",
      "Brithemandle",
      "Chaymelunder",
      "Mercylith",
    ],
};

export const GROUP_NAMES = {
  witchCovenFirst: [
    "Bleeding",
    "Bloody",
    "Chiming",
    "Cloaked",
    "Coiled",
    "Crooked",
    "Drowned",
    "Hatching",
    "Hidden",
    "Ivy-Crowned",
    "Liminal",
    "Silent",
    "Silver",
    "Singing",
    "Triple",
    "Twinned",
    "Veiled",
    "Virgin",
    "Wailing",
    "Whispering",
  ],
  witchCovenSecond: [
    "Blade",
    "Chalice",
    "Circle",
    "Crone",
    "Elm",
    "Hart",
    "Heart",
    "Holly",
    "Mandrake",
    "Moon",
    "Night",
    "Oak",
    "Palm",
    "Pentacle",
    "Raven",
    "River",
    "Serpent",
    "Solstice",
    "Well",
    "Wyrm",
  ],
  adventureParty: [
    "Treasure Seekers",
    "Iron Wreckers",
    "Furious Few",
    "Sparkle Squad",
    "High Hawks",
    "Order of the Sun",
    "Dirty Liar Crew",
    "Worthy Falcons",
    "Favoured Few",
    "Merry Goats",
    "Fellowship of the Goat",
    "Kingmakers",
    "Scarlet Friends",
    "Hearty Guardians",
    "West Stone Order",
    "Wild Company",
    "Freak Companions",
    "Champions of the Oath",
    "South Axe Heroes",
    "Graceful Society",
    "Comrades of the Green Fawn",
    "Knights of Hraigl",
    "Hard Brackenwolders",
    "Lamplighters",
    "Lantern Bearers",
    "Ebony Society",
    "White Servants",
    "Irregulars",
    "Ivy Comrades",
    "Winter Kindred",
    "Bar Burners",
    "Fallen Company",
    "Apple Dumpling Gang",
    "Dank Cellar Crew",
    "Dour Knights",
    "Protectors of the Doe",
    "Bandit Reformers",
    "Order of the Moss",
    "Moss Knights",
    "Society of the Stag",
    "Tower Rangers",
  ],
  banditCompany: [
    "River Gang",
    "Crimson Bandits",
    "Tunnel Snakes",
    "Gutter Runners",
    "Wood Rats",
    "Wolf Brothers",
    "Brave Boys",
    "Boiled Onion Gang",
    "Noosemen",
  ],
};

// Named, hex-located shrines for the Pilgrim encounter table.
export const LOST_SHRINES = [
  { name: "St Abthius", hex: "0406" },
  { name: "St Benester", hex: "1707" },
  { name: "St Clewyd", hex: "0906" },
  { name: "St Cornice", hex: "1505" },
  { name: "St Dank", hex: "0305" },
  { name: "St Eggort", hex: "0703" },
  { name: "St Elsa", hex: "0310" },
  { name: "St Faxis", hex: "1003" },
  { name: "St Galaunt", hex: "0607" },
  { name: "St Goodenough", hex: "1004" },
  { name: "St Gripe", hex: "1805" },
  { name: "St Hamfast", hex: "0309" },
  { name: "St Hollyhock", hex: "1005" },
  { name: "St Horace", hex: "1204" },
  { name: "St Jorrael", hex: "1705" },
  { name: "St Ponch", hex: "1010" },
  { name: "St Primula", hex: "1702" },
  { name: "St Quister", hex: "0302" },
  { name: "St Sedge", hex: "0202" },
  { name: "St Thorm", hex: "0911" },
  { name: "St Torphia", hex: "1402" },
  { name: "St Vinicus", hex: "0905" },
  { name: "St Whittery", hex: "1704" },
  { name: "St Willofrith", hex: "0404" },
  { name: "St Wort", hex: "1208" },
];

// ── Helpers ─────────────────────────────────────────────────────────────

const pick = arr => arr[Math.floor(Math.random() * arr.length)];

// Resolves Perchance-style inline choices, e.g. "{Jack|Jill}" -> "Jack" or "Jill".
function resolveBraces(str) {
  return str.replace(/\{([^}]+)\}/g, (_, options) => pick(options.split('|')));
}

export function randomGender() {
  return Math.random() < 0.5 ? 'masculine' : 'feminine';
}

/**
 * Returns "First Surname" for a kindred with gendered names, or a flat single
 * name for kindreds with no surnames (Elf, Frost Elf).
 * @param {string} kindred - a key of KINDRED_NAMES
 * @param {'masculine'|'feminine'} [gender]
 */
export function randomKindredName(kindred, gender = randomGender()) {
  const pool = KINDRED_NAMES[kindred];
  if (!pool) return null;
  if (pool.flat) {
    const first = resolveBraces(pick(pool.flat));
    return pool.surnames ? `${first} ${resolveBraces(pick(pool.surnames))}` : first;
  }
  return `${resolveBraces(pick(pool[gender]))} ${resolveBraces(pick(pool.surnames))}`;
}

// First name only, no surname — a few creature types (kelpie, ogre) go by a single name.
export function randomKindredFirstName(kindred, gender = randomGender()) {
  const pool = KINDRED_NAMES[kindred];
  if (!pool) return null;
  return resolveBraces(pick(pool.flat ?? pool[gender]));
}

export function randomMonsterName(speciesKey) {
  const pool = MONSTER_NAMES[speciesKey];
  return pool ? pick(pool) : null;
}

export function randomWitchName() {
  const kindred = Math.random() < 1 / 6 ? 'Noble' : 'Human';
  return {
    name: randomKindredName(kindred, 'feminine'),
    covenName: `${pick(GROUP_NAMES.witchCovenFirst)} ${pick(GROUP_NAMES.witchCovenSecond)}`,
  };
}

export function randomAdventurePartyName() {
  return pick(GROUP_NAMES.adventureParty);
}

export function randomBanditCompanyName() {
  return pick(GROUP_NAMES.banditCompany);
}

export function randomLostShrine() {
  return pick(LOST_SHRINES);
}

// ── Per-creature naming rules for the wilderness encounter tables ─────────
// Mirrors the source generator's "hasName" logic: only creature types listed
// here get a leader/individual name attached to their encounter. Keys are the
// exact creature-name strings used in dolmenwood-encounters.txt.
const SPECIES_NAME  = key            => ({ kind: 'species', key });
const KINDRED_NAME  = (kindred, gender) => ({ kind: 'kindred', kindred, gender });
const FIRST_NAME_ONLY = kindred      => ({ kind: 'firstOnly', kindred });

export const CREATURE_NAME_RULES = {
  // Species-specific name pools (MONSTER_NAMES)
  'BARROWBOGEY':          SPECIES_NAME('barrowbogey'),
  'BOGGIN':                SPECIES_NAME('boggin'),
  'CENTAUR-BESTIAL':      SPECIES_NAME('centaur_bestial'),
  'CENTAUR-SYLVAN':       SPECIES_NAME('centaur_sylvan'),
  'COBBIN':                SPECIES_NAME('cobbin'),
  'DEORLING-DOE':         SPECIES_NAME('deorling_doe'),
  'DEORLING-STAG':        SPECIES_NAME('deorling_stag'),
  'FAIRY HORSE':          SPECIES_NAME('fairy_horse'),
  'FOMORIAN':              SPECIES_NAME('fomorian'),
  'GHOUL':                 SPECIES_NAME('ghoul'),
  'GLOAM':                 SPECIES_NAME('gloam'),
  'GOBLIN':                SPECIES_NAME('goblin'),
  'HARPY':                 SPECIES_NAME('harpy'),
  'HARRIDAN':              SPECIES_NAME('harridan'),
  "JACK-O'-LANTERN":      SPECIES_NAME('jack_o_lantern'),
  'MADTOM':                SPECIES_NAME('madtom'),
  'MANTICORE':             SPECIES_NAME('manticore'),
  'MERFAUN':               SPECIES_NAME('merfaun'),
  'MOGGLEWOMP':            SPECIES_NAME('mogglewomp'),
  'NUTCAP':                SPECIES_NAME('nutcap'),
  'POOK MOREL':            SPECIES_NAME('pook_morel'),
  'REDCAP':                SPECIES_NAME('redcap'),
  'SCARECROW':             SPECIES_NAME('scarecrow'),
  'SCRABEY':               SPECIES_NAME('scrabey'),
  'SNAIL, GIANT-PSIONIC': SPECIES_NAME('snail_giant_psionic'),
  'SPECTRE':               SPECIES_NAME('spectre'),
  'SPRITE':                SPECIES_NAME('sprite'),
  'TALKING ANIMAL':       SPECIES_NAME('talking_animal'),
  'TREOWERE':              SPECIES_NAME('treowere'),
  'TROLL':                 SPECIES_NAME('troll'),
  'UNICORN-BLESSED':      SPECIES_NAME('unicorn_blessed'),
  'UNICORN-CORRUPT':      SPECIES_NAME('unicorn_corrupt'),
  'WODEWOSE':              SPECIES_NAME('wodewose'),
  'WYRM-BLACK BILE':      SPECIES_NAME('wyrm_black_bile'),
  'WYRM-BLOOD':            SPECIES_NAME('wyrm_blood'),
  'WYRM-PHLEGM':           SPECIES_NAME('wyrm_phlegm'),
  'WYRM-YELLOW BILE':     SPECIES_NAME('wyrm_yellow_bile'),

  // Kindred name-pool creatures (first + surname)
  'BREGGLE-LONGHORN':     KINDRED_NAME('Longhorn'),
  'BREGGLE-SHORTHORN':    KINDRED_NAME('Breggle'),
  'CROOKHORN':             KINDRED_NAME('Crookhorn'),
  'MOSSLING':              KINDRED_NAME('Mossling'),
  'MOULD ORACLE':         KINDRED_NAME('Mossling'),
  'WOODGRUE':              KINDRED_NAME('Woodgrue'),
  'WRONGUNCLE':            KINDRED_NAME('Human'),
  'WEREWOLF':              KINDRED_NAME('Human'),
  'SHAPE-STEALER':        KINDRED_NAME('Human'),
  'HEADLESS RIDER':       KINDRED_NAME('Human'),
  'SKELETON':              KINDRED_NAME('Human'),
  'DRUNE-COTTAGER':       KINDRED_NAME('Drune', 'masculine'),
  'DRUNE-AUDRUNE':        KINDRED_NAME('Drune'),
  'DRUNE-BRAITHMAID':     KINDRED_NAME('Drune', 'feminine'),
  'DRUNE-DRUNEWIFE':      KINDRED_NAME('Drune', 'feminine'),

  // Special cases
  'ELF-COURTIER':  { kind: 'elf' },
  'ELF-KNIGHT':    { kind: 'elf' },
  'ELF-WANDERER':  { kind: 'elf' },
  'GRIMALKIN':     { kind: 'grimalkin' },
  'BANSHEE':       { kind: 'banshee' },
  'WITCH':         { kind: 'witch' },

  // First name only, no surname
  'KELPIE': FIRST_NAME_ONLY('Human'),
  'OGRE':   FIRST_NAME_ONLY('Crookhorn'),
};

/**
 * Resolve a leader/individual name (and, for witches, a coven name) for a
 * wilderness-encounter creature entry, following the source generator's
 * per-species naming rules.
 * @param {string} creatureName - raw table entry name, e.g. "BARROWBOGEY", "TREOWERE (CHAOTIC)"
 * @returns {{ name: string|null, covenName: string|null }}
 */
export function nameForCreature(creatureName) {
  const key = creatureName.replace(/\s*\([^)]*\)\s*$/, '').trim();
  const rule = CREATURE_NAME_RULES[key];
  if (!rule) return { name: null, covenName: null };

  switch (rule.kind) {
    case 'species':
      return { name: randomMonsterName(rule.key), covenName: null };
    case 'kindred':
      return { name: randomKindredName(rule.kindred, rule.gender), covenName: null };
    case 'firstOnly':
      return { name: randomKindredFirstName(rule.kindred), covenName: null };
    case 'elf':
      // Source rolls a 20% chance (1d10 > 8) of being a Frost Elf instead of a Wood Elf.
      return { name: randomKindredName(Math.random() < 0.2 ? 'FrostElf' : 'Elf'), covenName: null };
    case 'grimalkin':
      return { name: randomKindredName('Grimalkin'), covenName: null };
    case 'banshee':
      return { name: randomKindredFirstName('FrostElf'), covenName: null };
    case 'witch': {
      const w = randomWitchName();
      return { name: w.name, covenName: w.covenName };
    }
    default:
      return { name: null, covenName: null };
  }
}
